// Copyright (c) 2026 Matthew Campion, PharmD; NexVigilant
// All Rights Reserved. See LICENSE file for details.

//! # EnergeticTransition
//!
//! **Tier**: T2-C (state + kappa + causality + N)
//! **Bridge**: energy (token metabolism) + state-os (state machines)
//! **Confidence**: 0.87
//!
//! Energy-aware state transitions. Each transition has a cost.
//! The system adapts transition selection based on available energy budget.

use core::fmt;

/// Energy regime (mirrors nexcore-energy).
///
/// ## Tier: T2-P (state + kappa)
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum EnergyRegime {
    /// Abundant energy — no restrictions.
    Surplus,
    /// Normal operating energy.
    Normal,
    /// Energy is scarce — prefer cheap transitions.
    Conservation,
    /// Critical energy — only essential transitions.
    Crisis,
}

/// A transition with associated energy cost.
///
/// ## Tier: T2-C (state + causality + N + kappa)
#[non_exhaustive]
#[derive(Debug, Clone)]
pub struct EnergeticTransition {
    /// Transition identifier.
    pub id: u32,
    /// Transition name.
    pub name: String,
    /// Source state.
    pub from: u32,
    /// Target state.
    pub to: u32,
    /// Token cost to execute this transition.
    pub cost: u64,
    /// Expected value generated by this transition.
    pub expected_value: f64,
    /// Minimum regime required to execute.
    pub min_regime: EnergyRegime,
}

impl EnergeticTransition {
    /// Value efficiency: expected_value / cost.
    #[must_use]
    #[allow(
        clippy::as_conversions,
        reason = "u64 to f64 for efficiency ratio; cost values fit safely in f64"
    )]
    pub fn efficiency(&self) -> f64 {
        if self.cost == 0 {
            return f64::MAX;
        }
        self.expected_value / self.cost as f64
    }

    /// Whether this transition is affordable in the given regime.
    #[must_use]
    pub fn is_affordable(&self, current_regime: EnergyRegime) -> bool {
        current_regime <= self.min_regime
    }
}

/// Token energy pool (simplified from nexcore-energy).
///
/// ## Tier: T2-P (N + state)
#[derive(Debug, Clone)]
pub struct TokenPool {
    /// Available tokens (ATP equivalent).
    pub available: u64,
    /// Total capacity.
    pub capacity: u64,
}

impl TokenPool {
    /// Create a new token pool.
    #[must_use]
    pub fn new(capacity: u64) -> Self {
        Self {
            available: capacity,
            capacity,
        }
    }

    /// Energy charge ratio (0.0 to 1.0).
    #[must_use]
    #[allow(
        clippy::as_conversions,
        reason = "u64 to f64 for charge ratio; token counts fit safely in f64"
    )]
    pub fn energy_charge(&self) -> f64 {
        if self.capacity == 0 {
            return 0.0;
        }
        self.available as f64 / self.capacity as f64
    }

    /// Current energy regime.
    #[must_use]
    pub fn regime(&self) -> EnergyRegime {
        let ec = self.energy_charge();
        if ec > 0.8 {
            EnergyRegime::Surplus
        } else if ec > 0.5 {
            EnergyRegime::Normal
        } else if ec > 0.2 {
            EnergyRegime::Conservation
        } else {
            EnergyRegime::Crisis
        }
    }

    /// Attempt to spend tokens. Returns true if successful.
    pub fn spend(&mut self, amount: u64) -> bool {
        if self.available >= amount {
            self.available = self.available.saturating_sub(amount);
            true
        } else {
            false
        }
    }

    /// Replenish tokens.
    pub fn replenish(&mut self, amount: u64) {
        self.available = self.available.saturating_add(amount).min(self.capacity);
    }
}

/// Energy-aware transition executor.
///
/// ## Tier: T2-C (state + kappa + causality + N)
/// Dominant: causality (cause = energy availability → effect = transition selection)
///
/// Innovation: bridges energy and state-os crates.
#[derive(Debug, Clone)]
pub struct EnergeticExecutor {
    /// Token pool.
    pool: TokenPool,
    /// Available transitions.
    transitions: Vec<EnergeticTransition>,
    /// Total transitions executed.
    executed_count: u64,
    /// Total tokens spent.
    total_spent: u64,
}

impl EnergeticExecutor {
    /// Create a new executor with a token pool.
    #[must_use]
    pub fn new(pool: TokenPool) -> Self {
        Self {
            pool,
            transitions: Vec::new(),
            executed_count: 0,
            total_spent: 0,
        }
    }

    /// Register a transition.
    pub fn register(&mut self, transition: EnergeticTransition) {
        self.transitions.push(transition);
    }

    /// Find the best affordable transition from a state.
    /// In conservation/crisis, selects highest-efficiency transition.
    #[must_use]
    pub fn best_transition(&self, from: u32) -> Option<&EnergeticTransition> {
        let regime = self.pool.regime();

        let mut candidates: Vec<&EnergeticTransition> = self
            .transitions
            .iter()
            .filter(|t| t.from == from && t.is_affordable(regime) && t.cost <= self.pool.available)
            .collect();

        match regime {
            EnergyRegime::Crisis | EnergyRegime::Conservation => {
                // Prefer efficiency in constrained regimes
                candidates.sort_by(|a, b| {
                    b.efficiency()
                        .partial_cmp(&a.efficiency())
                        .unwrap_or(core::cmp::Ordering::Equal)
                });
            }
            EnergyRegime::Surplus | EnergyRegime::Normal => {
                // Prefer value in abundant regimes
                candidates.sort_by(|a, b| {
                    b.expected_value
                        .partial_cmp(&a.expected_value)
                        .unwrap_or(core::cmp::Ordering::Equal)
                });
            }
        }

        candidates.first().copied()
    }

    /// Execute a transition, spending tokens.
    /// Returns the transition ID if successful.
    pub fn execute(&mut self, transition_id: u32) -> Option<u32> {
        let cost = self
            .transitions
            .iter()
            .find(|t| t.id == transition_id)
            .map(|t| t.cost)?;

        if self.pool.spend(cost) {
            self.executed_count = self.executed_count.saturating_add(1);
            self.total_spent = self.total_spent.saturating_add(cost);
            Some(transition_id)
        } else {
            None
        }
    }

    /// Current energy regime.
    #[must_use]
    pub fn regime(&self) -> EnergyRegime {
        self.pool.regime()
    }

    /// Available tokens.
    #[must_use]
    pub fn available_tokens(&self) -> u64 {
        self.pool.available
    }

    /// Replenish the token pool.
    pub fn replenish(&mut self, amount: u64) {
        self.pool.replenish(amount);
    }
}

impl fmt::Display for EnergeticExecutor {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "EnergeticExecutor({:?}, {}/{} tokens, {} executed)",
            self.pool.regime(),
            self.pool.available,
            self.pool.capacity,
            self.executed_count,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup_executor() -> EnergeticExecutor {
        let pool = TokenPool::new(1000);
        let mut exec = EnergeticExecutor::new(pool);

        exec.register(EnergeticTransition {
            id: 0,
            name: "expensive_but_valuable".into(),
            from: 0,
            to: 1,
            cost: 500,
            expected_value: 10.0,
            min_regime: EnergyRegime::Normal,
        });

        exec.register(EnergeticTransition {
            id: 1,
            name: "cheap_and_efficient".into(),
            from: 0,
            to: 1,
            cost: 50,
            expected_value: 3.0,
            min_regime: EnergyRegime::Crisis,
        });

        exec
    }

    #[test]
    fn test_surplus_prefers_value() {
        let exec = setup_executor();
        assert_eq!(exec.regime(), EnergyRegime::Surplus);

        let best = exec.best_transition(0);
        assert!(best.is_some());
        // In surplus, should prefer high-value (id=0, value=10.0)
        assert_eq!(best.map(|t| t.id), Some(0));
    }

    #[test]
    fn test_crisis_prefers_efficiency() {
        let mut exec = setup_executor();
        // Drain to crisis
        exec.pool.available = 100; // 10% = Crisis

        let best = exec.best_transition(0);
        assert!(best.is_some());
        // In crisis, should prefer efficient (id=1, 3.0/50 = 0.06 > 10.0/500 = 0.02)
        assert_eq!(best.map(|t| t.id), Some(1));
    }

    #[test]
    fn test_execute_spends_tokens() {
        let mut exec = setup_executor();
        assert_eq!(exec.available_tokens(), 1000);

        let result = exec.execute(0); // costs 500
        assert!(result.is_some());
        assert_eq!(exec.available_tokens(), 500);
    }

    #[test]
    fn test_insufficient_tokens() {
        let mut exec = setup_executor();
        exec.pool.available = 10; // can't afford anything meaningful

        let result = exec.execute(0); // costs 500
        assert!(result.is_none());
    }

    #[test]
    fn test_regime_classification() {
        let mut pool = TokenPool::new(100);
        assert_eq!(pool.regime(), EnergyRegime::Surplus);

        pool.available = 60;
        assert_eq!(pool.regime(), EnergyRegime::Normal);

        pool.available = 30;
        assert_eq!(pool.regime(), EnergyRegime::Conservation);

        pool.available = 10;
        assert_eq!(pool.regime(), EnergyRegime::Crisis);
    }
}
