//! #description
//!
//! Generated by RustForge.
use anyhow::{Context, Result};
use clap::Parser;
#[allow(unused_imports)]
use tracing::{info, warn, error, instrument};
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};
use std::io::{self, BufRead, Write};
use polars::prelude::*;
use pv_signal_detector::*;
/// Pipeline CLI arguments.
#[derive(Parser, Debug)]
#[command(name = "pv-signal-detector")]
#[command(version = "0.1.0")]
#[command(about = "Pharmacovigilance signal detection pipeline")]
struct Args {
    /// Run once and exit (default behavior).
    #[arg(long)]
    once: bool,
    /// Dry run - validate configuration only.
    #[arg(long)]
    dry_run: bool,
    /// Verbose output (-v, -vv, -vvv).
    #[arg(short, long, action = clap::ArgAction::Count)]
    verbose: u8,
}
#[derive(Debug, Default)]
struct PipelineStats {
    records_processed: u64,
    records_written: u64,
    duration_secs: f64,
}
#[tokio::main]
async fn main() -> Result<()> {
    let args = Args::parse();
    let level = match args.verbose {
        0 => tracing::Level::INFO,
        1 => tracing::Level::DEBUG,
        _ => tracing::Level::TRACE,
    };
    tracing_subscriber::registry()
        .with(tracing_subscriber::fmt::layer().with_target(true))
        .with(tracing_subscriber::filter::LevelFilter::from_level(level))
        .init();
    info!(pipeline = "pv-signal-detector", version = "0.1.0", "Starting pipeline");
    if args.dry_run {
        info!("Dry run mode - validation only");
        return Ok(());
    }
    let result = run_pipeline().await;
    match result {
        Ok(stats) => {
            info!(
                records_processed = stats.records_processed, records_written = stats
                .records_written, duration_secs = stats.duration_secs,
                "Pipeline completed successfully"
            );
            Ok(())
        }
        Err(e) => {
            error!(error = % e, "Pipeline failed");
            Err(e)
        }
    }
}
#[instrument]
async fn run_pipeline() -> Result<PipelineStats> {
    let start = std::time::Instant::now();
    let mut stats = PipelineStats::default();
    info!(stage = "faers-api", source_type = "HttpJson", "Starting HTTP ingest");
    let df = ingest_faers_api()
        .await
        .context(concat!("HTTP ingest failed: ", "faers-api"))?;
    stats.records_processed = df.height() as u64;
    info!(records = stats.records_processed, "Ingested records from HTTP");
    let df = df.lazy();
    info!(stage = "calculate-prr", operation = "Map", "Running transform");
    let df = transform_calculate_prr(df)
        .context(concat!("Transform failed: ", "calculate-prr"))?;
    info!(stage = "classify-signal", operation = "Filter", "Running transform");
    let df = transform_classify_signal(df)
        .context(concat!("Transform failed: ", "classify-signal"))?;
    info!(stage = "signal-output", sink_type = "JsonFile", "Running sink");
    panic!("Sink type not yet implemented: {}", "JsonFile");
    stats.duration_secs = start.elapsed().as_secs_f64();
    Ok(stats)
}
