// Copyright (c) 2026 NexVigilant LLC. All Rights Reserved.
// Intellectual Property of Matthew Alexander Campion, PharmD

//! Core types for the NMD spliceosome system.
//!
//! ## Primitive Grounding: sigma(Sequence) + boundary(d) + mapping(mu)
//!
//! EJC markers encode structural expectations as ordered sequences (sigma)
//! with boundary constraints (d) mapped from task specifications (mu).
//!
//! ## Biology Analog
//!
//! In biology, the spliceosome processes pre-mRNA by removing introns and
//! depositing Exon Junction Complexes (EJCs) at splice sites. These EJCs
//! serve as structural markers that the UPF surveillance complex later
//! checks during translation.
//!
//! Here, the spliceosome analyzes a task specification and deposits EJC
//! markers that encode structural expectations for pipeline execution.
//! The spliceosome never sees pipeline output — only task specs.

use serde::{Deserialize, Serialize};

/// Task category derived from empirical analysis of 151K tool calls.
///
/// Phase 0 taxonomy — data-derived, not invented.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaskCategory {
    /// Read/Grep/Glob dominant — information gathering
    Explore,
    /// Edit/Write/Bash dominant — code modification
    Mutate,
    /// Task/Team/SendMessage dominant — multi-agent coordination
    Orchestrate,
    /// MCP tool dominant — external computation
    Compute,
    /// Test/validation dominant — verification
    Verify,
    /// Browser automation dominant — UI interaction
    Browse,
    /// No single dominant category (>2 categories each >20%)
    Mixed,
}

impl TaskCategory {
    /// All defined categories.
    pub const ALL: [Self; 7] = [
        Self::Explore,
        Self::Mutate,
        Self::Orchestrate,
        Self::Compute,
        Self::Verify,
        Self::Browse,
        Self::Mixed,
    ];

    /// Human-readable label.
    #[must_use]
    pub fn label(self) -> &'static str {
        match self {
            Self::Explore => "explore",
            Self::Mutate => "mutate",
            Self::Orchestrate => "orchestrate",
            Self::Compute => "compute",
            Self::Verify => "verify",
            Self::Browse => "browse",
            Self::Mixed => "mixed",
        }
    }
}

/// Exon Junction Complex marker — a single structural expectation.
///
/// Deposited by the spliceosome before pipeline execution begins.
/// Consumed by UPF surveillance during co-translational monitoring.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EjcMarker {
    /// Expected execution phase identifier (sigma)
    pub phase_id: String,

    /// Expected tool categories for this phase (mu)
    pub expected_tool_categories: Vec<TaskCategory>,

    /// Grounding confidence threshold (f32, not bool)
    ///
    /// 0.0 = no grounding needed (pure exploration)
    /// 0.3 = light grounding (MCP tool call sufficient)
    /// 0.7 = moderate grounding (external data validation)
    /// 0.9 = heavy grounding (FAERS/regulatory data required)
    pub grounding_confidence_threshold: f32,

    /// Max tool calls before a checkpoint is required (d)
    pub max_calls_before_checkpoint: u32,

    /// Expected confidence band for assertions at this phase
    pub expected_confidence_range: (f32, f32),

    /// Whether this phase can be skipped without triggering anomaly
    pub skippable: bool,
}

/// Complete structural expectation for a pipeline run.
///
/// Generated by [`Spliceosome::splice()`] from a task specification.
/// Attached to `PipelineRun` as opaque JSON before execution begins.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TranscriptExpectation {
    /// Hash of the task specification (for cache/lookup)
    pub task_hash: String,

    /// Classified task category
    pub task_category: TaskCategory,

    /// Ordered sequence of EJC markers
    pub markers: Vec<EjcMarker>,

    /// Generator version for provenance tracking
    pub generator_version: String,

    /// Timestamp of generation
    pub generated_at: nexcore_chrono::DateTime,
}
