#![deny(unsafe_code)]
#![deny(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
//! NexCore Watch App — Pure Rust NativeActivity entry point with Slint UI.
//!
//! ## Architecture
//!
//! ```text
//! android_main()
//!   └── WatchSystem::boot(SystemConfig::default())
//!         ├── PVOS::boot()       ← 15-layer OS
//!         ├── SyncManager::new() ← background sync
//!         └── alert queue        ← bounded P0-P5 queue
//!                ↓
//!         Slint UI loop
//!           ├── GuardianScreen   ← ς state display
//!           ├── SignalScreen     ← κ metrics display
//!           └── AlertsScreen     ← ∂ priority display
//! ```
//!
//! ## Primitive Grounding
//! - × (Product): app = system × UI × platform
//! - σ (Sequence): boot → init_slint → event_loop
//! - → (Causality): system.tick() → UI property updates → render
//!
//! ## Tier: T3 (platform-specific, 100% Rust)

pub mod haptics;
pub mod input;
pub mod theme;
pub mod ui;

/// Android entry point — boots WatchSystem and runs Slint event loop.
///
/// ## Primitive: σ (Sequence) — boot → init → loop
/// ## Tier: T3
///
/// ## Pipeline
/// 1. Boot WatchSystem with default config (ς State)
/// 2. Initialize Slint UI from compiled .slint files (μ Mapping)
/// 3. Bind system state → Slint properties (→ Causality)
/// 4. Enter event loop (σ Sequence)
///
/// ## Gated: `#[cfg(target_os = "android")]`
/// On host, only the view model tests run. The entry point requires
/// the Android NativeActivity runtime provided by `android-activity`.
#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub fn android_main(app: slint::android::AndroidApp) {
    // Phase 1: Initialize Slint Android backend
    slint::android::init(app).ok();

    // Phase 2: Boot the watch system
    let mut system = nexcore_watch_core::WatchSystem::boot_default();

    // Phase 3: Create Slint UI
    // The NexVigilantWatch component is generated by slint-build from ui/app.slint
    let ui = NexVigilantWatch::new().ok();
    let Some(ui) = ui else { return };

    // Phase 4: Initial property binding — push system state to UI
    update_guardian_props(&ui, &system);
    update_signal_props(&ui, &system);
    update_alert_props(&ui, &system);

    // Phase 5: Wire navigation callback
    let ui_weak = ui.as_weak();
    ui.on_navigate(move |screen_index| {
        if let Some(ui) = ui_weak.upgrade() {
            ui.set_current_screen(screen_index);
        }
    });

    // Phase 6: Set up tick timer for periodic updates
    let ui_weak = ui.as_weak();
    let timer = slint::Timer::default();
    timer.start(
        slint::TimerMode::Repeated,
        core::time::Duration::from_secs(1),
        move || {
            if let Some(ui) = ui_weak.upgrade() {
                let now_ms = std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .map(|d| d.as_millis() as u64)
                    .unwrap_or(0);

                system.tick(now_ms);
                update_guardian_props(&ui, &system);
            }
        },
    );

    // Phase 7: Enter event loop (blocks until app exits)
    ui.run().ok();
}

/// Push Guardian status to Slint properties.
///
/// ## Primitive: μ (Mapping) — GuardianStatus → Slint props
#[cfg(target_os = "android")]
fn update_guardian_props(ui: &NexVigilantWatch, system: &nexcore_watch_core::WatchSystem) {
    let status = system.guardian_status();
    let vm = crate::ui::guardian_screen::GuardianViewModel::from_status(&status);

    ui.set_guardian_state_label(vm.state_label.into());
    ui.set_guardian_risk_fraction(vm.risk_fraction);
    ui.set_guardian_iteration_text(vm.iteration_text.into());
    ui.set_guardian_sensors(vm.sensors as i32);
    ui.set_guardian_actuators(vm.actuators as i32);
    ui.set_guardian_requires_attention(vm.requires_attention);

    // Color requires parsing hex → Slint Color
    let color = parse_hex_color(vm.state_color);
    ui.set_guardian_state_color(color);
}

/// Push latest signal result to Slint properties.
///
/// ## Primitive: μ (Mapping) — SignalResult → Slint props
#[cfg(target_os = "android")]
fn update_signal_props(ui: &NexVigilantWatch, _system: &nexcore_watch_core::WatchSystem) {
    // Signal screen shows the most recent detection
    // Will be updated when detect() is called
    ui.set_signal_drug("—".into());
    ui.set_signal_event("—".into());
    ui.set_signal_detected(false);
    ui.set_signal_text("NO SIGNAL".into());
}

/// Push alert queue to Slint properties.
///
/// ## Primitive: μ (Mapping) — Alert[] → Slint model
#[cfg(target_os = "android")]
fn update_alert_props(ui: &NexVigilantWatch, system: &nexcore_watch_core::WatchSystem) {
    ui.set_alert_count(system.alert_count() as i32);
}

/// Parse "#RRGGBB" hex string to Slint Color.
///
/// ## Primitive: μ (Mapping)
#[cfg(target_os = "android")]
fn parse_hex_color(hex: &str) -> slint::Color {
    let hex = hex.trim_start_matches('#');
    let r = u8::from_str_radix(&hex[0..2], 16).unwrap_or(0);
    let g = u8::from_str_radix(&hex[2..4], 16).unwrap_or(0);
    let b = u8::from_str_radix(&hex[4..6], 16).unwrap_or(0);
    slint::Color::from_rgb_u8(r, g, b)
}
