steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/nexcore/nexcore-api:latest'
      - '-f'
      - 'Dockerfile.api'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/nexcore/nexcore-api:latest'
timeout: '2400s'
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
