//! DNA-Based Spectral Vocabulary Optimization — SOP-001
//!
//! 6-phase pipeline: Fingerprint → Resonance → Classify → Spatial → Collisions → Architecture
//!
//! Generated by RustForge, implemented with nexcore-dna.

#![forbid(unsafe_code)]
#![deny(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use nexcore_dna::cortex;
use nexcore_dna::lexicon;
use nexcore_dna::statemind::StateMind;
use nexcore_dna::string_theory;
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

/// Pipeline input: anchor word + candidate list.
#[derive(Debug, Deserialize)]
pub struct VocabInput {
    pub anchor: String,
    pub candidates: Vec<String>,
}

// ---------------------------------------------------------------------------
// Phase 1: Anchor Fingerprint
// ---------------------------------------------------------------------------

/// Complete DNA fingerprint of the anchor word.
/// Tier: T3 (σ + μ + ν + N + κ)
#[derive(Debug, Serialize)]
pub struct AnchorFingerprint {
    pub word: String,
    pub strand_len: usize,
    pub entropy: f64,
    pub gc_content: f64,
    pub base_dist: [usize; 4],
    pub mean_tension: f64,
    pub peak_tension: f64,
    pub tension_variance: f64,
    pub dominant_period: usize,
    pub mode_count: usize,
    pub spectral_entropy: f64,
    pub energy_level: u32,
    pub total_energy: f64,
    pub energy_density: f64,
}

/// Phase 1: Encode anchor and compute full fingerprint.
pub fn phase1_fingerprint(anchor: &str) -> AnchorFingerprint {
    let ore = lexicon::mine(anchor);
    let tension = string_theory::word_tension(anchor);
    let spectrum = string_theory::word_spectrum(anchor);
    let energy = string_theory::string_energy(anchor);

    AnchorFingerprint {
        word: anchor.to_string(),
        strand_len: ore.length,
        entropy: ore.entropy,
        gc_content: ore.gc_content,
        base_dist: lexicon::nuc_distribution(&ore.strand),
        mean_tension: tension.mean_tension,
        peak_tension: tension.peak_tension,
        tension_variance: tension.variance,
        dominant_period: spectrum.dominant_period,
        mode_count: spectrum.modes.len(),
        spectral_entropy: spectrum.spectral_entropy,
        energy_level: energy.energy_level,
        total_energy: energy.total_energy,
        energy_density: energy.energy_density,
    }
}

// ---------------------------------------------------------------------------
// Phase 2: Resonance Screening
// ---------------------------------------------------------------------------

/// Resonance measurement for one candidate word.
/// Tier: T2-C (κ + ν + N + μ)
#[derive(Debug, Clone, Serialize)]
pub struct ResonanceResult {
    pub word: String,
    pub overlap: f64,
    pub harmony: f64,
    pub dissonance: f64,
    pub tension_alignment: f64,
    pub tier: u8,
    pub tier_name: String,
}

/// Phase 2: Compute resonance for all candidates and classify into tiers.
pub fn phase2_resonance(anchor: &str, candidates: &[String]) -> Vec<ResonanceResult> {
    let mut results: Vec<ResonanceResult> = candidates
        .iter()
        .map(|c| {
            let r = string_theory::word_resonance(anchor, c);
            let (tier, tier_name) = classify_harmony(r.harmony);
            ResonanceResult {
                word: c.clone(),
                overlap: r.overlap,
                harmony: r.harmony,
                dissonance: r.dissonance,
                tension_alignment: r.tension_alignment,
                tier,
                tier_name,
            }
        })
        .collect();

    // Sort: tier asc (best first), then overlap desc within tier
    results.sort_by(|a, b| {
        a.tier
            .cmp(&b.tier)
            .then_with(|| b.overlap.partial_cmp(&a.overlap).unwrap_or(std::cmp::Ordering::Equal))
    });

    results
}

/// Classify harmony score into tier.
fn classify_harmony(harmony: f64) -> (u8, String) {
    if (harmony - 1.0).abs() < f64::EPSILON {
        (1, "Pure Harmonic".to_string())
    } else if harmony > 0.5 {
        (2, "Favorable Tension".to_string())
    } else if (harmony - 0.5).abs() < f64::EPSILON {
        (3, "Creative Tension".to_string())
    } else {
        (4, "Dominant Dissonance".to_string())
    }
}

// ---------------------------------------------------------------------------
// Phase 2b: Tier Classification
// ---------------------------------------------------------------------------

/// Tier-grouped classification.
/// Tier: T2-C (σ + κ + μ)
#[derive(Debug, Serialize)]
pub struct TierClassification {
    pub tier1: Vec<ResonanceResult>,
    pub tier2: Vec<ResonanceResult>,
    pub tier3: Vec<ResonanceResult>,
    pub tier4: Vec<ResonanceResult>,
    pub summary: TierSummary,
}

#[derive(Debug, Serialize)]
pub struct TierSummary {
    pub tier1_count: usize,
    pub tier2_count: usize,
    pub tier3_count: usize,
    pub tier4_count: usize,
    pub total: usize,
}

/// Phase 2b: Group results by tier.
pub fn phase2b_classify(results: &[ResonanceResult]) -> TierClassification {
    let tier1: Vec<_> = results.iter().filter(|r| r.tier == 1).cloned().collect();
    let tier2: Vec<_> = results.iter().filter(|r| r.tier == 2).cloned().collect();
    let tier3: Vec<_> = results.iter().filter(|r| r.tier == 3).cloned().collect();
    let tier4: Vec<_> = results.iter().filter(|r| r.tier == 4).cloned().collect();

    let summary = TierSummary {
        tier1_count: tier1.len(),
        tier2_count: tier2.len(),
        tier3_count: tier3.len(),
        tier4_count: tier4.len(),
        total: results.len(),
    };

    TierClassification {
        tier1,
        tier2,
        tier3,
        tier4,
        summary,
    }
}

// ---------------------------------------------------------------------------
// Phase 3: Spatial Analysis
// ---------------------------------------------------------------------------

/// 3D word-space point.
#[derive(Debug, Serialize)]
pub struct SpatialPoint {
    pub word: String,
    pub entropy: f64,
    pub gc: f64,
    pub density: f64,
}

/// Cluster membership.
#[derive(Debug, Serialize)]
pub struct SpatialCluster {
    pub id: usize,
    pub members: Vec<String>,
    pub centroid: [f64; 3],
    pub radius: f64,
    pub cluster_type: String,
}

/// Complete spatial topology.
/// Tier: T3 (σ + μ + N + λ + κ)
#[derive(Debug, Serialize)]
pub struct TopologyMap {
    pub points: Vec<SpatialPoint>,
    pub clusters: Vec<SpatialCluster>,
    pub centroid: [f64; 3],
    pub radius: f64,
    pub anchor_cluster_id: Option<usize>,
}

/// Phase 3: Project into 3D and cluster.
pub fn phase3_spatial(anchor: &str, candidates: &[String]) -> TopologyMap {
    let mut mind = StateMind::new();
    mind.ingest(anchor);
    for c in candidates {
        mind.ingest(c);
    }

    // Extract points
    let entries = mind.lexicon().entries();
    let mind_points = mind.points();
    let points: Vec<SpatialPoint> = entries
        .iter()
        .zip(mind_points.iter())
        .map(|(ore, pt)| SpatialPoint {
            word: ore.word.clone(),
            entropy: pt.entropy_norm,
            gc: pt.gc_content,
            density: pt.density,
        })
        .collect();

    let centroid = mind.centroid();
    let radius = mind.radius();

    // K-means cluster
    let k = ((entries.len() as f64) / 3.0).ceil() as usize;
    let k = k.max(2).min(entries.len());
    let cluster_result = cortex::kmeans(&mind, k, 20);

    // Find which cluster contains anchor
    let anchor_idx = entries.iter().position(|e| e.word == anchor);
    let anchor_cluster_id = anchor_idx.and_then(|ai| {
        cluster_result
            .clusters
            .iter()
            .find(|c| c.members.contains(&ai))
            .map(|c| c.id)
    });

    // Build spatial clusters with type labels
    let clusters: Vec<SpatialCluster> = cluster_result
        .clusters
        .iter()
        .map(|c| {
            let members: Vec<String> = c
                .members
                .iter()
                .filter_map(|&idx| entries.get(idx).map(|e| e.word.clone()))
                .collect();

            let cluster_type = if Some(c.id) == anchor_cluster_id {
                "Identity"
            } else if members.len() == 1 {
                "Singleton"
            } else {
                "Satellite"
            };

            SpatialCluster {
                id: c.id,
                members,
                centroid: c.centroid.as_array(),
                radius: c.radius,
                cluster_type: cluster_type.to_string(),
            }
        })
        .collect();

    TopologyMap {
        points,
        clusters,
        centroid: centroid.as_array(),
        radius,
        anchor_cluster_id,
    }
}

// ---------------------------------------------------------------------------
// Phase 4: Collision Detection
// ---------------------------------------------------------------------------

/// A collision between two spectrally identical words.
#[derive(Debug, Serialize)]
pub struct Collision {
    pub word_a: String,
    pub word_b: String,
    pub overlap: f64,
    pub same_cluster: bool,
}

/// Collision report.
/// Tier: T2-C (κ + ∂ + σ)
#[derive(Debug, Serialize)]
pub struct CollisionReport {
    pub collisions: Vec<Collision>,
    pub degenerate_clusters: Vec<usize>,
    pub clean: bool,
}

/// Phase 4: Detect collisions within Tier 1.
pub fn phase4_collisions(tier1: &[ResonanceResult], topology: &TopologyMap) -> CollisionReport {
    let mut collisions = Vec::new();

    for i in 0..tier1.len() {
        for j in (i + 1)..tier1.len() {
            let r = string_theory::word_resonance(&tier1[i].word, &tier1[j].word);
            let same = same_cluster(&tier1[i].word, &tier1[j].word, topology);
            if r.overlap > 0.97 && same {
                collisions.push(Collision {
                    word_a: tier1[i].word.clone(),
                    word_b: tier1[j].word.clone(),
                    overlap: r.overlap,
                    same_cluster: true,
                });
            }
        }
    }

    let degenerate_clusters: Vec<usize> = topology
        .clusters
        .iter()
        .filter(|c| c.radius < 0.03 && c.members.len() > 1)
        .map(|c| c.id)
        .collect();

    let clean = collisions.is_empty() && degenerate_clusters.is_empty();

    CollisionReport {
        collisions,
        degenerate_clusters,
        clean,
    }
}

/// Check if two words are in the same cluster.
fn same_cluster(a: &str, b: &str, topology: &TopologyMap) -> bool {
    topology.clusters.iter().any(|c| {
        c.members.iter().any(|m| m == a) && c.members.iter().any(|m| m == b)
    })
}

// ---------------------------------------------------------------------------
// Phase 5: Energy Compatibility
// ---------------------------------------------------------------------------

/// Energy level for a single word.
#[derive(Debug, Serialize)]
pub struct WordEnergy {
    pub word: String,
    pub energy_level: u32,
    pub total_energy: f64,
}

/// Energy compatibility assessment.
/// Tier: T2-C (N + κ + ∂)
#[derive(Debug, Serialize)]
pub struct EnergyAssessment {
    pub anchor_level: u32,
    pub word_levels: Vec<WordEnergy>,
    pub min_level: u32,
    pub max_level: u32,
    pub spread: u32,
    pub status: String,
}

/// Phase 5: Check energy compatibility of Tier 1 words.
pub fn phase5_energy(anchor_energy: u32, tier1: &[ResonanceResult]) -> EnergyAssessment {
    let word_levels: Vec<WordEnergy> = tier1
        .iter()
        .map(|r| {
            let e = string_theory::string_energy(&r.word);
            WordEnergy {
                word: r.word.clone(),
                energy_level: e.energy_level,
                total_energy: e.total_energy,
            }
        })
        .collect();

    let min_level = word_levels
        .iter()
        .map(|w| w.energy_level)
        .min()
        .unwrap_or(anchor_energy);
    let max_level = word_levels
        .iter()
        .map(|w| w.energy_level)
        .max()
        .unwrap_or(anchor_energy);
    let spread = max_level.saturating_sub(min_level);

    let status = if spread <= 2 {
        "acceptable"
    } else if spread == 3 {
        "warning"
    } else {
        "reject"
    };

    EnergyAssessment {
        anchor_level: anchor_energy,
        word_levels,
        min_level,
        max_level,
        spread,
        status: status.to_string(),
    }
}

// ---------------------------------------------------------------------------
// Phase 6: Vocabulary Architecture
// ---------------------------------------------------------------------------

/// A reframe entry: Tier 4 word → suggested replacement.
#[derive(Debug, Serialize)]
pub struct ReframeEntry {
    pub avoid: String,
    pub avoid_harmony: f64,
    pub replace_with: String,
    pub replace_harmony: f64,
}

/// Final vocabulary architecture — 4 concentric rings.
/// Tier: T3 (σ + μ + κ + ∂ + N + λ)
#[derive(Debug, Serialize)]
pub struct VocabArchitecture {
    pub anchor: String,
    pub core_identity: Vec<String>,
    pub mission_ring: Vec<String>,
    pub operational_ring: Vec<String>,
    pub reframe_list: Vec<ReframeEntry>,
    pub energy_status: String,
    pub collision_clean: bool,
}

/// Phase 6: Assemble the final vocabulary architecture.
pub fn phase6_architecture(
    anchor: &str,
    tiers: &TierClassification,
    topology: &TopologyMap,
    energy: &EnergyAssessment,
    collisions: &CollisionReport,
) -> VocabArchitecture {
    // Core Identity: Tier 1 words in the anchor's cluster (up to 5)
    let anchor_members: Vec<String> = topology
        .anchor_cluster_id
        .and_then(|id| topology.clusters.iter().find(|c| c.id == id))
        .map(|c| c.members.clone())
        .unwrap_or_default();

    let core_identity: Vec<String> = tiers
        .tier1
        .iter()
        .filter(|r| anchor_members.contains(&r.word))
        .map(|r| r.word.clone())
        .take(5)
        .collect();

    // Mission Ring: Tier 1 words NOT in anchor cluster (up to 8)
    let mission_ring: Vec<String> = tiers
        .tier1
        .iter()
        .filter(|r| !anchor_members.contains(&r.word))
        .map(|r| r.word.clone())
        .take(8)
        .collect();

    // Operational Ring: Tier 2 + Tier 3 by overlap (up to 12)
    let operational_ring: Vec<String> = tiers
        .tier2
        .iter()
        .chain(tiers.tier3.iter())
        .map(|r| r.word.clone())
        .take(12)
        .collect();

    // Reframe List: Tier 4 words → best Tier 1/2 substitute
    let reframe_list: Vec<ReframeEntry> = tiers
        .tier4
        .iter()
        .map(|t4| {
            let best_sub = tiers
                .tier1
                .iter()
                .chain(tiers.tier2.iter())
                .max_by(|a, b| {
                    a.overlap
                        .partial_cmp(&b.overlap)
                        .unwrap_or(std::cmp::Ordering::Equal)
                });
            ReframeEntry {
                avoid: t4.word.clone(),
                avoid_harmony: t4.harmony,
                replace_with: best_sub
                    .map(|s| s.word.clone())
                    .unwrap_or_default(),
                replace_harmony: best_sub.map(|s| s.harmony).unwrap_or(0.0),
            }
        })
        .collect();

    VocabArchitecture {
        anchor: anchor.to_string(),
        core_identity,
        mission_ring,
        operational_ring,
        reframe_list,
        energy_status: energy.status.clone(),
        collision_clean: collisions.clean,
    }
}

// ---------------------------------------------------------------------------
// Full Report
// ---------------------------------------------------------------------------

/// Complete SOP-001 report combining all 6 phases.
#[derive(Debug, Serialize)]
pub struct FullReport {
    pub sop: String,
    pub version: String,
    pub fingerprint: AnchorFingerprint,
    pub resonance_table: Vec<ResonanceResult>,
    pub tiers: TierClassification,
    pub topology: TopologyMap,
    pub collisions: CollisionReport,
    pub energy: EnergyAssessment,
    pub architecture: VocabArchitecture,
}

/// Execute the complete 6-phase pipeline.
pub fn run_pipeline(input: &VocabInput) -> FullReport {
    // Phase 1: Anchor Fingerprint
    let fingerprint = phase1_fingerprint(&input.anchor);

    // Phase 2: Resonance Screening
    let resonance_table = phase2_resonance(&input.anchor, &input.candidates);

    // Phase 2b: Tier Classification
    let tiers = phase2b_classify(&resonance_table);

    // Phase 3: Spatial Analysis
    let topology = phase3_spatial(&input.anchor, &input.candidates);

    // Phase 4: Collision Detection
    let collisions = phase4_collisions(&tiers.tier1, &topology);

    // Phase 5: Energy Compatibility
    let energy = phase5_energy(fingerprint.energy_level, &tiers.tier1);

    // Phase 6: Vocabulary Architecture
    let architecture = phase6_architecture(
        &input.anchor,
        &tiers,
        &topology,
        &energy,
        &collisions,
    );

    FullReport {
        sop: "SOP-001".to_string(),
        version: "1.0".to_string(),
        fingerprint,
        resonance_table,
        tiers,
        topology,
        collisions,
        energy,
        architecture,
    }
}
