//! dna-vocab-optimizer — SOP-001 CLI
//!
//! Usage:
//!   echo '{"anchor":"NexVigilant","candidates":["vigilance","patient",...]}' | dna-vocab-optimizer
//!   dna-vocab-optimizer --anchor NexVigilant --candidates vigilance,patient,clarity,...
//!   dna-vocab-optimizer --anchor NexVigilant --file candidates.txt
//!
//! Generated by RustForge, implemented with nexcore-dna.

#![forbid(unsafe_code)]
#![deny(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use anyhow::{Context, Result};
use clap::Parser;
use dna_vocab_optimizer::{FullReport, VocabInput, run_pipeline};
use std::io::{self, Read};
use tracing::info;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

/// DNA-Based Spectral Vocabulary Optimization — SOP-001
#[derive(Parser, Debug)]
#[command(name = "dna-vocab-optimizer")]
#[command(version = "0.1.0")]
#[command(about = "6-phase DNA spectral vocabulary optimization per SOP-001")]
struct Args {
    /// Anchor word (brand/product name)
    #[arg(long)]
    anchor: Option<String>,

    /// Comma-separated candidate words
    #[arg(long)]
    candidates: Option<String>,

    /// File with one candidate word per line
    #[arg(long)]
    file: Option<String>,

    /// Output file path (default: stdout)
    #[arg(short, long)]
    output: Option<String>,

    /// Pretty-print JSON output
    #[arg(long, default_value_t = true)]
    pretty: bool,

    /// Verbose output (-v, -vv, -vvv)
    #[arg(short, long, action = clap::ArgAction::Count)]
    verbose: u8,
}

fn main() -> Result<()> {
    let args = Args::parse();

    let level = match args.verbose {
        0 => tracing::Level::WARN,
        1 => tracing::Level::INFO,
        2 => tracing::Level::DEBUG,
        _ => tracing::Level::TRACE,
    };
    tracing_subscriber::registry()
        .with(tracing_subscriber::fmt::layer().with_target(false).with_level(true))
        .with(tracing_subscriber::filter::LevelFilter::from_level(level))
        .init();

    // Parse input
    let input = parse_input(&args).context("Failed to parse input")?;

    info!(
        anchor = %input.anchor,
        candidates = input.candidates.len(),
        "Running SOP-001 pipeline"
    );

    // Run pipeline
    let start = std::time::Instant::now();
    let report = run_pipeline(&input);
    let elapsed = start.elapsed();

    info!(
        tier1 = report.tiers.summary.tier1_count,
        tier2 = report.tiers.summary.tier2_count,
        tier3 = report.tiers.summary.tier3_count,
        tier4 = report.tiers.summary.tier4_count,
        duration_ms = elapsed.as_millis() as u64,
        "Pipeline complete"
    );

    // Output
    output_report(&report, &args).context("Failed to write output")?;

    // Summary to stderr
    print_summary(&report, elapsed);

    Ok(())
}

fn parse_input(args: &Args) -> Result<VocabInput> {
    // Mode 1: --anchor + --candidates or --file
    if let Some(anchor) = &args.anchor {
        let candidates = if let Some(csv) = &args.candidates {
            csv.split(',').map(|s| s.trim().to_string()).collect()
        } else if let Some(path) = &args.file {
            let content =
                std::fs::read_to_string(path).with_context(|| format!("Cannot read {path}"))?;
            content
                .lines()
                .map(|l| l.trim().to_string())
                .filter(|l| !l.is_empty() && !l.starts_with('#'))
                .collect()
        } else {
            anyhow::bail!("Provide --candidates or --file with --anchor");
        };

        return Ok(VocabInput {
            anchor: anchor.clone(),
            candidates,
        });
    }

    // Mode 2: JSON from stdin
    let mut buf = String::new();
    io::stdin()
        .read_to_string(&mut buf)
        .context("Failed to read stdin")?;

    if buf.trim().is_empty() {
        anyhow::bail!(
            "No input. Use --anchor/--candidates flags or pipe JSON to stdin.\n\
             Example: echo '{{\"anchor\":\"Brand\",\"candidates\":[\"word1\",\"word2\"]}}' | dna-vocab-optimizer"
        );
    }

    serde_json::from_str(&buf).context("Failed to parse JSON from stdin")
}

fn output_report(report: &FullReport, args: &Args) -> Result<()> {
    let json = if args.pretty {
        serde_json::to_string_pretty(report).context("Failed to serialize report")?
    } else {
        serde_json::to_string(report).context("Failed to serialize report")?
    };

    if let Some(path) = &args.output {
        std::fs::write(path, &json).with_context(|| format!("Cannot write to {path}"))?;
        eprintln!("Report written to {path}");
    } else {
        println!("{json}");
    }

    Ok(())
}

fn print_summary(report: &FullReport, elapsed: std::time::Duration) {
    eprintln!();
    eprintln!("=== SOP-001 Vocabulary Optimization Report ===");
    eprintln!();
    eprintln!(
        "Anchor: {} (T_dom={}, E_level={}, {} nt)",
        report.fingerprint.word,
        report.fingerprint.dominant_period,
        report.fingerprint.energy_level,
        report.fingerprint.strand_len,
    );
    eprintln!();
    eprintln!("Candidates tested: {}", report.tiers.summary.total);
    eprintln!(
        "  Tier 1 (Pure Harmonic):      {}",
        report.tiers.summary.tier1_count
    );
    eprintln!(
        "  Tier 2 (Favorable Tension):  {}",
        report.tiers.summary.tier2_count
    );
    eprintln!(
        "  Tier 3 (Creative Tension):   {}",
        report.tiers.summary.tier3_count
    );
    eprintln!(
        "  Tier 4 (Dominant Dissonance): {}",
        report.tiers.summary.tier4_count
    );
    eprintln!();
    eprintln!("Core Identity Ring:");
    for w in &report.architecture.core_identity {
        eprintln!("  + {w}");
    }
    eprintln!("Mission Ring:");
    for w in &report.architecture.mission_ring {
        eprintln!("  + {w}");
    }
    if !report.architecture.reframe_list.is_empty() {
        eprintln!("Reframe:");
        for r in &report.architecture.reframe_list {
            eprintln!("  {} -> {}", r.avoid, r.replace_with);
        }
    }
    eprintln!();
    eprintln!(
        "Collisions: {}  Energy: {}  Duration: {:.0}ms",
        if report.collisions.clean {
            "clean"
        } else {
            "DETECTED"
        },
        report.energy.status,
        elapsed.as_secs_f64() * 1000.0,
    );
}
