//! SessionStart hook: git_context
//!
//! Generated by hook-scaffold.

use claude_hooks::{
    exit_success, read_input, write_text,
    input::SessionStartInput,
    HookResult,
};

use std::process::Command;

fn get_git_info() -> Option<String> {
    let branch = Command::new("git")
        .args(["rev-parse", "--abbrev-ref", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())?;

    let last_commit = Command::new("git")
        .args(["log", "-1", "--oneline"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())?;

    Some(format!(
        "Development context: Current git branch is '{}'. Last commit: '{}'",
        branch, last_commit
    ))
}

fn main() -> HookResult<()> {
    let _input: SessionStartInput = read_input()?;

    if let Some(git_info) = get_git_info() {
        // Write context as plain text (will be added to the model's context)
        write_text(&git_info)?;
    }

    exit_success();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_git_info_is_not_empty_if_in_repo() {
        // We're likely in a git repo during development
        if let Some(info) = get_git_info() {
            assert!(info.contains("branch"));
            assert!(info.contains("commit"));
        }
    }
}
