//! # The Treasury Act (Economic Sovereignty)
//!
//! Implementation of the economic primitives required for the Guardian x Polymarket
//! integration. This module grounds market-based resource allocation into
//! T1/T2 universals.

use nexcore_primitives::measurement::Confidence;
use serde::{Deserialize, Serialize};

// ============================================================================
// T1: UNIVERSAL PRIMITIVES (ECONOMICS)
// ============================================================================

/// T1: Token - The irreducible unit of value.
/// Grounding: Axiom: Exchange.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct Token(pub u64);

/// T1: Side - The directional preference in a market.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Side {
    /// Betting on the occurrence (e.g., Signal is Valid).
    Yes,
    /// Betting against the occurrence (e.g., Signal is False Positive).
    No,
}

// ============================================================================
// T2-P: QUANTITIES
// ============================================================================

/// T2-P: Odds - The quantified probability expressed as a ratio (0.0 to 1.0).
/// Grounds to T1: f64.
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct Odds(f64);

impl Odds {
    pub fn new(value: f64) -> Self {
        Self(value.clamp(0.01, 0.99)) // Prevent 0/1 for market liquidity
    }

    pub fn value(self) -> f64 {
        self.0
    }

    /// Convert Odds to implied Confidence.
    pub fn as_confidence(self) -> Confidence {
        Confidence::new(self.0)
    }
}

/// T2-P: Liquidity - The depth of tokens available for exchange.
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct Liquidity(u64);

impl Liquidity {
    pub fn new(tokens: u64) -> Self {
        Self(tokens)
    }

    pub fn value(self) -> u64 {
        self.0
    }
}

/// T2-P: Asymmetry - The delta between system confidence and market odds.
/// This represents the "Value" generated by Guardian intelligence.
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct Asymmetry(f64);

impl Asymmetry {
    pub fn calculate(internal: Confidence, market: Odds) -> Self {
        Self((internal.value() - market.value()).abs())
    }

    pub fn is_actionable(&self, threshold: f64) -> bool {
        self.0 >= threshold
    }
}

// ============================================================================
// T2-C: COMPOSITES
// ============================================================================

/// T2-C: MarketState - The current economic status of a predictive resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketState {
    pub market_id: String,
    pub odds: Odds,
    pub liquidity: Liquidity,
}

/// T2-C: Position - An agent's stake in a market.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Position {
    pub agent_id: String,
    pub side: Side,
    pub stake: Token,
}

impl MarketState {
    /// Calculate the cost of acquiring a position.
    pub fn calculate_cost(&self, tokens: Token, side: Side) -> Token {
        let price = match side {
            Side::Yes => self.odds.value(),
            Side::No => 1.0 - self.odds.value(),
        };
        Token((tokens.0 as f64 * price) as u64)
    }
}
