[hold]
name = "core-primitives"
owner = "core-primitives-team"
review_required = true
layer = "Domain"
members = ["nexcore-bicone", "nexcore-chrono", "nexcore-codec", "nexcore-config", "nexcore-constants", "nexcore-core", "nexcore-domain-primitives", "nexcore-error", "nexcore-error-derive", "nexcore-hash", "nexcore-id", "nexcore-init", "nexcore-lex-primitiva", "nexcore-primitive-scanner", "nexcore-primitives", "nexcore-rh-proofs", "nucli", "primitive-innovation"]
