//! Drift Detection for Phase 4 Surveillance

use serde::{Deserialize, Serialize};
use std::collections::VecDeque;

/// Trend direction for metric analysis
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TrendDirection {
    /// Metric is improving
    Improving,
    /// Metric is stable
    Stable,
    /// Metric is degrading
    Degrading,
    /// Insufficient data
    Unknown,
}

impl TrendDirection {
    /// Returns emoji representation
    ///
    /// # Returns
    /// Static string with emoji
    pub fn emoji(&self) -> &'static str {
        match self {
            Self::Improving => "📈",
            Self::Stable => "➡️",
            Self::Degrading => "📉",
            Self::Unknown => "❓",
        }
    }
}

/// Alert generated by drift detection
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DriftAlert {
    /// Unix timestamp
    pub timestamp: f64,
    /// Severity level (0-3)
    pub severity: u8,
    /// Alert message
    pub message: String,
    /// Current metric value
    pub current_value: f64,
    /// Threshold that was breached
    pub threshold: f64,
    /// Current trend direction
    pub trend: TrendDirection,
}

/// Drift detector for Phase 4 surveillance
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DriftDetector {
    target: f64,
    alert: f64,
    history: VecDeque<(f64, f64)>,
    max_history: usize,
    baseline: Option<f64>,
    alerts: u32,
    last_alert: Option<f64>,
    cooldown: f64,
}

impl DriftDetector {
    /// Creates a new drift detector
    ///
    /// # Arguments
    /// * `target` - Target threshold (good when above)
    /// * `alert` - Alert threshold (alert when below)
    ///
    /// # Returns
    /// New DriftDetector instance
    pub fn new(target: f64, alert: f64) -> Self {
        Self {
            target,
            alert,
            history: VecDeque::new(),
            max_history: 1000,
            baseline: None,
            alerts: 0,
            last_alert: None,
            cooldown: 3600.0,
        }
    }

    /// Records a metric value
    ///
    /// # Arguments
    /// * `value` - The metric value to record
    pub fn record(&mut self, value: f64) {
        self.history.push_front((crate::state::now(), value));
        if self.history.len() > self.max_history {
            self.history.pop_back();
        }
        if self.baseline.is_none() && self.history.len() >= 10 {
            self.baseline = Some(self.history.iter().take(10).map(|(_, v)| v).sum::<f64>() / 10.0);
        }
    }

    /// Returns the most recent value
    ///
    /// # Returns
    /// Most recent value or None if empty
    pub fn current(&self) -> Option<f64> {
        self.history.front().map(|(_, v)| *v)
    }

    /// Returns the established baseline
    ///
    /// # Returns
    /// Baseline value or None if not established
    pub fn baseline(&self) -> Option<f64> {
        self.baseline
    }

    /// Checks if value is below alert threshold
    ///
    /// # Arguments
    /// * `v` - Value to check
    ///
    /// # Returns
    /// True if drifting (below alert threshold)
    pub fn is_drifting(&self, v: f64) -> bool {
        v < self.alert
    }

    /// Checks if value meets target threshold
    ///
    /// # Arguments
    /// * `v` - Value to check
    ///
    /// # Returns
    /// True if value meets or exceeds target
    pub fn meets_target(&self, v: f64) -> bool {
        v >= self.target
    }

    /// Calculates trend direction from history
    ///
    /// # Returns
    /// TrendDirection based on recent vs older values
    pub fn trend(&self) -> TrendDirection {
        if self.history.len() < 10 {
            return TrendDirection::Unknown;
        }
        let recent: f64 = self.history.iter().take(5).map(|(_, v)| v).sum::<f64>() / 5.0;
        let older: f64 = self
            .history
            .iter()
            .skip(5)
            .take(5)
            .map(|(_, v)| v)
            .sum::<f64>()
            / 5.0;
        if recent - older > 0.05 {
            TrendDirection::Improving
        } else if recent - older < -0.05 {
            TrendDirection::Degrading
        } else {
            TrendDirection::Stable
        }
    }

    /// Checks current value and generates alert if needed
    ///
    /// # Arguments
    /// * `current` - Current metric value
    ///
    /// # Returns
    /// DriftAlert if alerting, None otherwise
    pub fn check_and_alert(&mut self, current: f64) -> Option<DriftAlert> {
        self.record(current);
        let now = crate::state::now();
        if self.last_alert.map_or(false, |l| now - l < self.cooldown) {
            return None;
        }
        if self.is_drifting(current) {
            self.alerts += 1;
            self.last_alert = Some(now);
            Some(DriftAlert {
                timestamp: now,
                severity: self.alerts.min(3) as u8,
                message: format!("{:.1}% < {:.1}%", current * 100.0, self.alert * 100.0),
                current_value: current,
                threshold: self.alert,
                trend: self.trend(),
            })
        } else {
            self.alerts = 0;
            None
        }
    }

    /// Calculates drift score (0.0 = no drift, 1.0 = max drift)
    ///
    /// # Returns
    /// Drift score as f64 between 0.0 and 1.0
    pub fn drift_score(&self) -> f64 {
        let (c, b) = (self.current().unwrap_or(0.0), self.baseline.unwrap_or(1.0));
        if b == 0.0 {
            0.0
        } else {
            ((b - c) / b).clamp(0.0, 1.0)
        }
    }

    /// Generates a status report
    ///
    /// # Returns
    /// Formatted status string
    pub fn report(&self) -> String {
        let c = self.current().unwrap_or(0.0);
        let s = if self.meets_target(c) {
            "✅"
        } else if self.is_drifting(c) {
            "🚨"
        } else {
            "⚠️"
        };
        format!(
            "{} {:.1}% {:?} drift={:.2}",
            s,
            c * 100.0,
            self.trend(),
            self.drift_score()
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_drift_thresholds() {
        let d = DriftDetector::new(0.80, 0.70);
        assert!(d.is_drifting(0.60));
        assert!(!d.is_drifting(0.75));
        assert!(d.meets_target(0.85));
        assert!(!d.meets_target(0.75));
    }

    #[test]
    fn test_trend_detection() {
        let mut d = DriftDetector::new(0.80, 0.70);
        for v in [0.85, 0.82, 0.78, 0.75, 0.72, 0.70, 0.68, 0.65, 0.62, 0.60] {
            d.record(v);
        }
        assert_eq!(d.trend(), TrendDirection::Degrading);
    }
}
