//! # Capability 14: Public Health Act (HHS Domain)
//!
//! Implementation of the Public Health Act as a core structural
//! capability within the HUD domain. This capability manages the
//! "Signal Validation" and "Efficacy Measurement" of the Union.
//!
//! Matches 1:1 to the US Department of Health and Human Services (HHS)
//! mandate to enhance the health and well-being of all Americans.
//!
//! ## HHS Agency Mappings
//! - **FDA (Validation):** Verifies the safety and efficacy of detected signals.
//! - **CDC (Epidemiology):** Tracks the "Spread" and "Impact" of signals across the community.
//! - **NIH (Research):** Conducts deep-dive analysis into signal causality and mechanism.
//! - **CMS (Value):** Measures the value-based outcome and economic impact of signals.

use nexcore_primitives::measurement::{Confidence, Measured};
use serde::{Deserialize, Serialize};

/// T3: PublicHealthAct - Capability 14 of 37.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublicHealthAct {
    /// The unique capability identifier.
    pub id: String,
    /// Whether the signal validation engine is currently active.
    pub validation_engine_active: bool,
}

/// T2-S: SignalEfficacy - The quantified accuracy of a signal against ground truth.
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct SignalEfficacy(pub f64);

/// T2-V: ValidationAudit - The formal review of a signal's "Public Health" impact.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidationAudit {
    /// The identifier of the signal being validated.
    pub signal_id: String,
    /// The efficacy score (accuracy) of the signal.
    pub efficacy_score: f64,
    /// The calculated false positive rate.
    pub false_positive_rate: f64,
    /// The modeled economic/community value generated by this signal.
    pub community_value_generated: f64,
}

impl PublicHealthAct {
    /// Creates a new instance of the PublicHealthAct.
    pub fn new() -> Self {
        Self {
            id: "CAP-014".into(),
            validation_engine_active: true,
        }
    }

    /// Validate a signal's efficacy against ground truth (FDA-style validation).
    pub fn validate_signal(&self, signal_id: &str, accuracy: f64) -> Measured<ValidationAudit> {
        let audit = ValidationAudit {
            signal_id: signal_id.to_string(),
            efficacy_score: accuracy,
            false_positive_rate: 1.0 - accuracy,
            community_value_generated: accuracy * 100.0, // Placeholder for value modeling
        };

        let confidence = if accuracy > 0.6 {
            Confidence::new(0.9)
        } else {
            Confidence::new(0.5)
        };

        Measured::uncertain(audit, confidence)
    }

    /// Measure the "Public Health" impact of a signal suite (CDC/CMS metrics).
    pub fn measure_impact(&self, total_signals: u32, valid_signals: u32) -> SignalEfficacy {
        if total_signals == 0 {
            return SignalEfficacy(0.0);
        }
        SignalEfficacy(valid_signals as f64 / total_signals as f64)
    }
}
