//! #description
//!
//! Generated by RustForge.
use nexcore_error::{Context, Result};
use clap::Parser;
use polars::prelude::*;
use std::io::{self, BufRead, Write};
#[allow(unused_imports)]
use tracing::{error, info, instrument, warn};
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};
use transformer_primitives::*;
/// Pipeline CLI arguments.
#[derive(Parser, Debug)]
#[command(name = "transformer-primitives")]
#[command(version = "0.1.0")]
#[command(
    about = "Transformer attention mechanism modeled as data pipeline: token embedding → self-attention → feed-forward → prediction"
)]
struct Args {
    /// Run once and exit (default behavior).
    #[arg(long)]
    once: bool,
    /// Dry run - validate configuration only.
    #[arg(long)]
    dry_run: bool,
    /// Verbose output (-v, -vv, -vvv).
    #[arg(short, long, action = clap::ArgAction::Count)]
    verbose: u8,
}
#[derive(Debug, Default)]
struct PipelineStats {
    records_processed: u64,
    records_written: u64,
    duration_secs: f64,
}
#[tokio::main]
async fn main() -> Result<()> {
    let args = Args::parse();
    let level = match args.verbose {
        0 => tracing::Level::INFO,
        1 => tracing::Level::DEBUG,
        _ => tracing::Level::TRACE,
    };
    tracing_subscriber::registry()
        .with(tracing_subscriber::fmt::layer().with_target(true))
        .with(tracing_subscriber::filter::LevelFilter::from_level(level))
        .init();
    info!(
        pipeline = "transformer-primitives",
        version = "0.1.0",
        "Starting pipeline"
    );
    if args.dry_run {
        info!("Dry run mode - validation only");
        return Ok(());
    }
    let result = run_pipeline().await;
    match result {
        Ok(stats) => {
            info!(
                records_processed = stats.records_processed,
                records_written = stats.records_written,
                duration_secs = stats.duration_secs,
                "Pipeline completed successfully"
            );
            Ok(())
        }
        Err(e) => {
            error!(error = % e, "Pipeline failed");
            Err(e)
        }
    }
}
#[instrument]
async fn run_pipeline() -> Result<PipelineStats> {
    let start = std::time::Instant::now();
    let mut stats = PipelineStats::default();
    info!(
        stage = "token-embedding",
        source_type = "Stdin",
        "Reading from stdin"
    );
    let stdin = io::stdin();
    let lines: Vec<String> = stdin
        .lock()
        .lines()
        .filter_map(|line| line.ok())
        .filter(|line| !line.trim().is_empty())
        .collect();
    let json_str = if lines.len() == 1 && lines[0].trim().starts_with('[') {
        lines[0].clone()
    } else {
        format!("[{}]", lines.join(","))
    };
    let cursor = std::io::Cursor::new(json_str);
    let df = JsonReader::new(cursor)
        .finish()
        .context("Failed to parse JSON from stdin")?;
    stats.records_processed = df.height() as u64;
    info!(
        records = stats.records_processed,
        "Ingested records from stdin"
    );
    let df = df.lazy();
    info!(
        stage = "positional-encoding",
        operation = "Map",
        "Running transform"
    );
    let df = transform_positional_encoding(df)
        .context(concat!("Transform failed: ", "positional-encoding"))?;
    info!(
        stage = "qkv-projection",
        operation = "Map",
        "Running transform"
    );
    let df =
        transform_qkv_projection(df).context(concat!("Transform failed: ", "qkv-projection"))?;
    info!(
        stage = "attention-scores",
        operation = "Map",
        "Running transform"
    );
    let df = transform_attention_scores(df)
        .context(concat!("Transform failed: ", "attention-scores"))?;
    info!(
        stage = "softmax-normalize",
        operation = "Map",
        "Running transform"
    );
    let df = transform_softmax_normalize(df)
        .context(concat!("Transform failed: ", "softmax-normalize"))?;
    info!(
        stage = "weighted-values",
        operation = "Aggregate",
        "Running transform"
    );
    let df =
        transform_weighted_values(df).context(concat!("Transform failed: ", "weighted-values"))?;
    info!(
        stage = "residual-connection",
        operation = "Map",
        "Running transform"
    );
    let df = transform_residual_connection(df)
        .context(concat!("Transform failed: ", "residual-connection"))?;
    info!(
        stage = "feed-forward",
        operation = "Map",
        "Running transform"
    );
    let df = transform_feed_forward(df).context(concat!("Transform failed: ", "feed-forward"))?;
    info!(
        stage = "token-prediction",
        sink_type = "JsonFile",
        "Running sink"
    );
    nexcore_error::bail!("Sink type not yet implemented: JsonFile");
}
