//! Marketplace commission calculations.
//!
//! The platform takes a commission on marketplace transactions:
//! - **CRO orders**: 3-8% sliding scale based on order value
//! - **AI model revenue**: 20-30% (default 25%)
//! - **Expert engagements**: 15% flat
//! - **Deal brokerage**: 1-3% sliding scale based on deal value
//!
//! All calculations use integer cents via [`Money`] to avoid rounding errors.

use serde::{Deserialize, Serialize};
use vr_core::Money;

/// Commission rate category for marketplace transactions.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CommissionRate {
    /// CRO order commission: 3-8% sliding scale.
    CroOrder,
    /// AI model marketplace commission: 20-30%.
    AiModel,
    /// Expert engagement commission: 15% flat.
    Expert,
    /// Deal brokerage commission: 1-3% sliding scale.
    DealBrokerage,
}

/// Calculate commission on a CRO (Contract Research Organization) order.
///
/// Sliding scale based on order value:
/// - < $10,000: 8%
/// - $10,000 - $49,999.99: 6%
/// - $50,000 - $99,999.99: 5%
/// - >= $100,000: 3%
///
/// # Arguments
/// * `order_value` - Total CRO order value in USD cents
///
/// # Returns
/// Commission amount in USD cents
#[must_use]
pub fn calculate_cro_commission(order_value: Money) -> Money {
    let cents = order_value.cents();
    let bps = if cents < 1_000_000 {
        // < $10,000 → 8% = 800 bps
        800
    } else if cents < 5_000_000 {
        // $10,000 - $49,999.99 → 6% = 600 bps
        600
    } else if cents < 10_000_000 {
        // $50,000 - $99,999.99 → 5% = 500 bps
        500
    } else {
        // >= $100,000 → 3% = 300 bps
        300
    };
    order_value.percent_bps(bps)
}

/// Calculate commission on AI model marketplace revenue.
///
/// Default rate: 25% of model revenue.
///
/// # Arguments
/// * `revenue` - Total revenue generated by the model in USD cents
///
/// # Returns
/// Commission amount in USD cents
#[must_use]
pub fn calculate_model_commission(revenue: Money) -> Money {
    // 25% = 2500 bps
    revenue.percent_bps(2_500)
}

/// Calculate commission on expert engagement fees.
///
/// Flat rate: 15% of engagement fee.
///
/// # Arguments
/// * `engagement_fee` - Total expert engagement fee in USD cents
///
/// # Returns
/// Commission amount in USD cents
#[must_use]
pub fn calculate_expert_commission(engagement_fee: Money) -> Money {
    // 15% = 1500 bps
    engagement_fee.percent_bps(1_500)
}

/// Calculate commission on deal brokerage.
///
/// Sliding scale based on deal value:
/// - < $1,000,000: 3%
/// - $1,000,000 - $9,999,999.99: 2%
/// - >= $10,000,000: 1%
///
/// # Arguments
/// * `deal_value` - Total deal value in USD cents
///
/// # Returns
/// Commission amount in USD cents
#[must_use]
pub fn calculate_deal_commission(deal_value: Money) -> Money {
    let cents = deal_value.cents();
    let bps = if cents < 100_000_000 {
        // < $1,000,000 → 3% = 300 bps
        300
    } else if cents < 1_000_000_000 {
        // $1M - $9,999,999.99 → 2% = 200 bps
        200
    } else {
        // >= $10,000,000 → 1% = 100 bps
        100
    };
    deal_value.percent_bps(bps)
}

/// Summary of all marketplace commissions for a billing period.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommissionSummary {
    /// Total CRO order commissions.
    pub cro_total: Money,
    /// Total AI model commissions.
    pub model_total: Money,
    /// Total expert engagement commissions.
    pub expert_total: Money,
    /// Total deal brokerage commissions.
    pub deal_total: Money,
    /// Grand total of all commissions.
    pub grand_total: Money,
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    // ---- CRO Commission Tests ----

    #[test]
    fn cro_commission_small_order() {
        // $5,000 order → 8% = $400
        let order = Money::usd_dollars(5_000);
        let commission = calculate_cro_commission(order);
        assert_eq!(commission.cents(), 40_000); // $400.00
        assert_eq!(commission.to_string(), "$400.00");
    }

    #[test]
    fn cro_commission_medium_order() {
        // $25,000 order → 6% = $1,500
        let order = Money::usd_dollars(25_000);
        let commission = calculate_cro_commission(order);
        assert_eq!(commission.cents(), 150_000); // $1,500.00
        assert_eq!(commission.to_string(), "$1500.00");
    }

    #[test]
    fn cro_commission_large_order() {
        // $75,000 order → 5% = $3,750
        let order = Money::usd_dollars(75_000);
        let commission = calculate_cro_commission(order);
        assert_eq!(commission.cents(), 375_000); // $3,750.00
        assert_eq!(commission.to_string(), "$3750.00");
    }

    #[test]
    fn cro_commission_very_large_order() {
        // $500,000 order → 3% = $15,000
        let order = Money::usd_dollars(500_000);
        let commission = calculate_cro_commission(order);
        assert_eq!(commission.cents(), 1_500_000); // $15,000.00
        assert_eq!(commission.to_string(), "$15000.00");
    }

    #[test]
    fn cro_commission_boundary_10k() {
        // Exactly $10,000 → 6% bracket
        let order = Money::usd_dollars(10_000);
        let commission = calculate_cro_commission(order);
        assert_eq!(commission.cents(), 60_000); // $600.00
    }

    #[test]
    fn cro_commission_just_below_10k() {
        // $9,999.99 → 8% bracket
        let order = Money::usd(999_999);
        let commission = calculate_cro_commission(order);
        // 999,999 * 800 / 10,000 = 79,999 cents = $799.99
        assert_eq!(commission.cents(), 79_999);
    }

    #[test]
    fn cro_commission_boundary_100k() {
        // Exactly $100,000 → 3% bracket
        let order = Money::usd_dollars(100_000);
        let commission = calculate_cro_commission(order);
        assert_eq!(commission.cents(), 300_000); // $3,000.00
    }

    // ---- AI Model Commission Tests ----

    #[test]
    fn model_commission_standard() {
        // $10,000 model revenue → 25% = $2,500
        let revenue = Money::usd_dollars(10_000);
        let commission = calculate_model_commission(revenue);
        assert_eq!(commission.cents(), 250_000); // $2,500.00
        assert_eq!(commission.to_string(), "$2500.00");
    }

    #[test]
    fn model_commission_small() {
        // $100 model revenue → 25% = $25
        let revenue = Money::usd_dollars(100);
        let commission = calculate_model_commission(revenue);
        assert_eq!(commission.cents(), 2_500); // $25.00
    }

    // ---- Expert Commission Tests ----

    #[test]
    fn expert_commission_standard() {
        // $5,000 engagement → 15% = $750
        let fee = Money::usd_dollars(5_000);
        let commission = calculate_expert_commission(fee);
        assert_eq!(commission.cents(), 75_000); // $750.00
        assert_eq!(commission.to_string(), "$750.00");
    }

    #[test]
    fn expert_commission_hourly() {
        // $500/hr * 8 hours = $4,000 → 15% = $600
        let fee = Money::usd_dollars(4_000);
        let commission = calculate_expert_commission(fee);
        assert_eq!(commission.cents(), 60_000); // $600.00
    }

    // ---- Deal Brokerage Commission Tests ----

    #[test]
    fn deal_commission_small() {
        // $500,000 deal → 3% = $15,000
        let deal = Money::usd_dollars(500_000);
        let commission = calculate_deal_commission(deal);
        assert_eq!(commission.cents(), 1_500_000); // $15,000.00
        assert_eq!(commission.to_string(), "$15000.00");
    }

    #[test]
    fn deal_commission_medium() {
        // $5,000,000 deal → 2% = $100,000
        let deal = Money::usd_dollars(5_000_000);
        let commission = calculate_deal_commission(deal);
        assert_eq!(commission.cents(), 10_000_000); // $100,000.00
        assert_eq!(commission.to_string(), "$100000.00");
    }

    #[test]
    fn deal_commission_large() {
        // $50,000,000 deal → 1% = $500,000
        let deal = Money::usd_dollars(50_000_000);
        let commission = calculate_deal_commission(deal);
        assert_eq!(commission.cents(), 50_000_000); // $500,000.00
        assert_eq!(commission.to_string(), "$500000.00");
    }

    #[test]
    fn deal_commission_boundary_1m() {
        // Exactly $1,000,000 → 2% bracket
        let deal = Money::usd_dollars(1_000_000);
        let commission = calculate_deal_commission(deal);
        assert_eq!(commission.cents(), 2_000_000); // $20,000.00
    }

    #[test]
    fn deal_commission_boundary_10m() {
        // Exactly $10,000,000 → 1% bracket
        let deal = Money::usd_dollars(10_000_000);
        let commission = calculate_deal_commission(deal);
        assert_eq!(commission.cents(), 10_000_000); // $100,000.00
    }

    #[test]
    fn deal_commission_just_below_1m() {
        // $999,999.99 → 3% bracket
        let deal = Money::usd(99_999_999);
        let commission = calculate_deal_commission(deal);
        // 99,999,999 * 300 / 10,000 = 2,999,999 cents = $29,999.99
        assert_eq!(commission.cents(), 2_999_999);
    }

    // ---- Zero Value Tests ----

    #[test]
    fn commission_on_zero_is_zero() {
        let zero = Money::usd(0);
        assert_eq!(calculate_cro_commission(zero).cents(), 0);
        assert_eq!(calculate_model_commission(zero).cents(), 0);
        assert_eq!(calculate_expert_commission(zero).cents(), 0);
        assert_eq!(calculate_deal_commission(zero).cents(), 0);
    }
}
