//! UI mapping export and code generation

use super::{error::Result, types::*};
use std::fs;
use std::path::Path;

/// Generator for exporting UI mappings to various formats
pub struct UiMappingGenerator;

impl UiMappingGenerator {
    /// Export mappings to YAML file
    pub fn to_yaml_file<P: AsRef<Path>>(mappings: &[UiMapping], path: P) -> Result<()> {
        let yaml = Self::to_yaml(mappings)?;
        fs::write(path, yaml)?;
        Ok(())
    }

    /// Export mappings to YAML string
    pub fn to_yaml(mappings: &[UiMapping]) -> Result<String> {
        serde_yaml::to_string(mappings).map_err(|e| e.into())
    }

    /// Export mappings to JSON file
    pub fn to_json_file<P: AsRef<Path>>(mappings: &[UiMapping], path: P) -> Result<()> {
        let json = Self::to_json(mappings)?;
        fs::write(path, json)?;
        Ok(())
    }

    /// Export mappings to JSON string (pretty-printed)
    pub fn to_json(mappings: &[UiMapping]) -> Result<String> {
        serde_json::to_string_pretty(mappings).map_err(|e| e.into())
    }

    /// Generate TypeScript type definitions for UI mappings
    pub fn to_typescript_types(mappings: &[UiMapping]) -> String {
        let mut output = String::new();

        output.push_str("// Auto-generated UI mappings from CLI specification\n");
        output.push_str("// DO NOT EDIT - Generated by cli-ui-mapper\n\n");

        // Generate route constants
        output.push_str("export const ROUTES = {\n");
        for mapping in mappings {
            let route_name = mapping
                .route
                .replace(['/', '-'], "_")
                .trim_start_matches('_')
                .to_uppercase();
            output.push_str(&format!("  {}: '{}',\n", route_name, mapping.route));
        }
        output.push_str("} as const;\n\n");

        // Generate mapping type
        output.push_str("export interface UiMapping {\n");
        output.push_str("  route: string;\n");
        output.push_str("  pageType: 'Form' | 'Dashboard' | 'List' | 'Detail' | 'Settings';\n");
        output.push_str("  title: string;\n");
        output.push_str("  components: UiComponent[];\n");
        output.push_str("  cliCommandPath: string[];\n");
        output.push_str("}\n\n");

        output.push_str("export interface UiComponent {\n");
        output.push_str("  type: ComponentType;\n");
        output.push_str("  label: string;\n");
        output.push_str("  mapsTo: string;\n");
        output.push_str("  required: boolean;\n");
        output.push_str("  help?: string;\n");
        output.push_str("  default?: string;\n");
        output.push_str("}\n\n");

        output.push_str("export type ComponentType =\n");
        output.push_str("  | { type: 'TextField' }\n");
        output.push_str("  | { type: 'NumberInput'; min?: number; max?: number }\n");
        output.push_str("  | { type: 'Select'; options: string[] }\n");
        output.push_str("  | { type: 'Toggle' }\n");
        output.push_str("  | { type: 'FileUpload'; accept?: string };\n\n");

        // Generate mappings constant
        output.push_str("export const UI_MAPPINGS: UiMapping[] = ");
        if let Ok(json) = serde_json::to_string_pretty(mappings) {
            output.push_str(&json);
        }
        output.push_str(";\n");

        output
    }

    /// Generate Rust route definitions
    pub fn to_rust_routes(mappings: &[UiMapping]) -> String {
        let mut output = String::new();

        output.push_str("// Auto-generated routes from CLI specification\n");
        output.push_str("// DO NOT EDIT - Generated by cli-ui-mapper\n\n");

        output.push_str("pub mod routes {\n");
        for mapping in mappings {
            let const_name = mapping
                .route
                .replace(['/', '-'], "_")
                .trim_start_matches('_')
                .to_uppercase();
            output.push_str(&format!(
                "    pub const {}: &str = \"{}\";\n",
                const_name, mapping.route
            ));
        }
        output.push_str("}\n\n");

        output.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        output.push_str("pub enum AppRoute {\n");
        for mapping in mappings {
            let variant = Self::to_pascal_case(
                mapping
                    .route
                    .replace(['/', '-'], "_")
                    .trim_start_matches('_'),
            );
            output.push_str(&format!("    {},\n", variant));
        }
        output.push_str("}\n\n");

        output.push_str("impl AppRoute {\n");
        output.push_str("    pub fn path(&self) -> &'static str {\n");
        output.push_str("        match self {\n");
        for mapping in mappings {
            let variant = Self::to_pascal_case(
                mapping
                    .route
                    .replace(['/', '-'], "_")
                    .trim_start_matches('_'),
            );
            output.push_str(&format!(
                "            AppRoute::{} => \"{}\",\n",
                variant, mapping.route
            ));
        }
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");

        // Add main function for example compilation
        output.push_str("fn main() {\n");
        output.push_str("    println!(\"Available routes:\");\n");
        if let Some(first_mapping) = mappings.first() {
            let first_variant = Self::to_pascal_case(
                first_mapping
                    .route
                    .replace(['/', '-'], "_")
                    .trim_start_matches('_'),
            );
            output.push_str(&format!(
                "    println!(\"  {{:?}} -> {{}}\", AppRoute::{}, AppRoute::{}.path());\n",
                first_variant, first_variant
            ));
        }
        output.push_str("}\n");

        output
    }

    /// Generate a summary report of the mappings
    pub fn generate_report(cli: &CliCommand, mappings: &[UiMapping]) -> String {
        let mut report = String::new();

        report.push_str("# CLI-UI Mapping Report\n\n");
        report.push_str(&format!("**CLI Command**: {}\n", cli.name));
        report.push_str(&format!("**Description**: {}\n\n", cli.description));

        report.push_str("## Generated Pages\n\n");
        report.push_str("| Route | Page Type | Components | CLI Command |\n");
        report.push_str("|-------|-----------|------------|-------------|\n");

        for mapping in mappings {
            report.push_str(&format!(
                "| {} | {:?} | {} | {} |\n",
                mapping.route,
                mapping.page_type,
                mapping.components.len(),
                mapping.cli_command_path.join(" ")
            ));
        }

        report.push_str("\n## Component Mappings\n\n");
        for mapping in mappings {
            report.push_str(&format!("### {} ({})\n\n", mapping.title, mapping.route));

            if !mapping.components.is_empty() {
                report.push_str("| Component | Maps To | Type | Required |\n");
                report.push_str("|-----------|---------|------|----------|\n");

                for comp in &mapping.components {
                    report.push_str(&format!(
                        "| {} | `{}` | {:?} | {} |\n",
                        comp.label,
                        comp.maps_to,
                        comp.component_type,
                        if comp.required { "✓" } else { "" }
                    ));
                }
                report.push('\n');
            }
        }

        report
    }

    fn to_pascal_case(s: &str) -> String {
        s.split('_')
            .filter(|s| !s.is_empty())
            .map(|word| {
                let mut chars = word.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().chain(chars).collect(),
                }
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(
            UiMappingGenerator::to_pascal_case("test_route"),
            "TestRoute"
        );
        assert_eq!(
            UiMappingGenerator::to_pascal_case("guardian_scan"),
            "GuardianScan"
        );
    }

    #[test]
    fn test_to_json() {
        let mapping = UiMapping {
            route: "/test".to_string(),
            page_type: PageType::Form,
            title: "Test".to_string(),
            components: vec![],
            navigation: NavPosition {
                parent: None,
                order: 0,
                icon: None,
            },
            output_display: None,
            cli_command_path: vec!["test".to_string()],
        };

        let json = UiMappingGenerator::to_json(&[mapping]).unwrap();
        assert!(json.contains("\"route\": \"/test\""));
    }

    #[test]
    fn test_hyphenated_routes_converted_to_valid_identifiers() {
        let mapping = UiMapping {
            route: "/crate-lens/my-route".to_string(),
            page_type: PageType::Form,
            title: "Test".to_string(),
            components: vec![],
            navigation: NavPosition {
                parent: None,
                order: 0,
                icon: None,
            },
            output_display: None,
            cli_command_path: vec!["crate-lens".to_string(), "my-route".to_string()],
        };

        // Test Rust output has valid identifiers (no hyphens)
        let rust_output = UiMappingGenerator::to_rust_routes(&[mapping.clone()]);
        assert!(rust_output.contains("CRATE_LENS_MY_ROUTE"));
        assert!(rust_output.contains("CrateLensMyRoute"));
        assert!(!rust_output.contains("CRATE-LENS"));
        assert!(!rust_output.contains("Crate-lens"));

        // Test TypeScript output has valid identifiers (no hyphens in keys)
        let ts_output = UiMappingGenerator::to_typescript_types(&[mapping]);
        assert!(ts_output.contains("CRATE_LENS_MY_ROUTE"));
        assert!(!ts_output.contains("CRATE-LENS"));
    }
}
