//! Pipeline ingest, transform, and sink functions.
//!
//! Generated by RustForge.

#![deny(clippy::unwrap_used)]
#![deny(clippy::expect_used)]
#![deny(clippy::panic)]
#![warn(missing_docs)]
use nexcore_dataframe::{Agg, DataFrame};

/// Ingest from HTTP endpoint: #url
pub async fn ingest_classification_data() -> nexcore_error::Result<DataFrame> {
    use nexcore_error::Context;
    use std::time::Duration;
    tracing::info!(
        stage = "classification-data",
        url = "http://localhost:3030/api/v1/lex_primitiva/types",
        "Starting HTTP ingest"
    );
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(30u64))
        .build()
        .context("Failed to build HTTP client")?;
    let headers = reqwest::header::HeaderMap::new();
    let mut all_records: Vec<serde_json::Value> = Vec::new();
    let request_url = "http://localhost:3030/api/v1/lex_primitiva/types".to_string();
    let page_count = 1u32;
    tracing::debug!(page = page_count, url = % request_url, "Fetching page");
    let request = client
        .request(reqwest::Method::GET, &request_url)
        .headers(headers.clone());
    let response = retry_request(&client, request, 3u32).await?;
    let json: serde_json::Value = response
        .json()
        .await
        .context("Failed to parse JSON response")?;
    let data = json;
    match &data {
        serde_json::Value::Array(arr) => {
            if arr.is_empty() {
                tracing::info!(pages = page_count, "No more records, stopping pagination");
            } else {
                all_records.extend(arr.clone());
            }
        }
        obj @ serde_json::Value::Object(_) => {
            all_records.push(obj.clone());
        }
        serde_json::Value::Null
        | serde_json::Value::Bool(_)
        | serde_json::Value::Number(_)
        | serde_json::Value::String(_) => {
            tracing::warn!("Unexpected response type, treating as single record");
            all_records.push(data.clone());
        }
    }
    tracing::info!(
        stage = "classification-data",
        total_records = all_records.len(),
        pages = page_count,
        "HTTP ingest complete"
    );
    let json_str = serde_json::to_string(&all_records).context("Failed to serialize records")?;
    let df = DataFrame::from_json(&json_str)
        .map_err(|e| nexcore_error::nexerror!("Failed to parse records into DataFrame: {e}"))?;
    Ok(df)
}
/// Retry HTTP request with exponential backoff.
async fn retry_request(
    client: &reqwest::Client,
    request: reqwest::RequestBuilder,
    max_retries: u32,
) -> nexcore_error::Result<reqwest::Response> {
    use nexcore_error::Context;
    use std::time::Duration;
    let mut last_error = None;
    for retry in 0..=max_retries {
        let req = request
            .try_clone()
            .ok_or_else(|| nexcore_error::nexerror!("Failed to clone request for retry"))?;
        match req.send().await {
            Ok(resp) if resp.status().is_success() => {
                return Ok(resp);
            }
            Ok(resp) if resp.status().as_u16() == 429 => {
                let backoff = resp
                    .headers()
                    .get("retry-after")
                    .and_then(|v: &reqwest::header::HeaderValue| v.to_str().ok())
                    .and_then(|s: &str| s.parse::<u64>().ok())
                    .unwrap_or(2_u64.pow(retry));
                tracing::warn!(
                    retry = retry,
                    backoff_secs = backoff,
                    "Rate limited (429), backing off"
                );
                tokio::time::sleep(Duration::from_secs(backoff)).await;
                last_error = Some(nexcore_error::nexerror!(
                    "Rate limited after {} retries",
                    retry.saturating_add(1)
                ));
            }
            Ok(resp) if resp.status().is_server_error() => {
                let status = resp.status();
                let backoff = 2_u64.pow(retry);
                tracing::warn!(
                    retry = retry, status = % status, backoff_secs = backoff,
                    "Server error, retrying"
                );
                tokio::time::sleep(Duration::from_secs(backoff)).await;
                last_error = Some(nexcore_error::nexerror!("Server error: {}", status));
            }
            Ok(resp) => {
                let status = resp.status();
                let body: String = resp.text().await.unwrap_or_default();
                return Err(nexcore_error::nexerror!("HTTP error {}: {}", status, body));
            }
            Err(e) => {
                let backoff = 2_u64.pow(retry);
                tracing::warn!(
                    retry = retry, error = % e, backoff_secs = backoff,
                    "Network error, retrying"
                );
                tokio::time::sleep(Duration::from_secs(backoff)).await;
                last_error = Some(nexcore_error::nexerror!("Network error: {}", e));
            }
        }
    }
    Err(last_error.unwrap_or_else(|| {
        nexcore_error::nexerror!("Request failed after {} retries", max_retries)
    }))
}
/// Extract nested data using a simple JSONPath-like notation.
fn extract_json_path(
    json: &serde_json::Value,
    path: &str,
) -> nexcore_error::Result<serde_json::Value> {
    let mut current = json.clone();
    for segment in path.trim_start_matches("$.").split('.') {
        if let Some(idx) = segment.find('[') {
            let key = segment.get(..idx).unwrap_or_default();
            let start = idx.saturating_add(1);
            let end = segment.len().saturating_sub(1);
            let bracket_content = segment.get(start..end).unwrap_or_default();
            if !key.is_empty() {
                current = current
                    .get(key)
                    .cloned()
                    .ok_or_else(|| nexcore_error::nexerror!("Path segment '{}' not found", key))?;
            }
            if bracket_content == "*" {
            } else if let Ok(index) = bracket_content.parse::<usize>() {
                current = current.get(index).cloned().ok_or_else(|| {
                    nexcore_error::nexerror!("Array index {} out of bounds", index)
                })?;
            }
        } else {
            current = current
                .get(segment)
                .cloned()
                .ok_or_else(|| nexcore_error::nexerror!("Path segment '{}' not found", segment))?;
        }
    }
    Ok(current)
}
/// Transform: filter
/// Expression: #expr_str
pub fn transform_filter_new_types(df: DataFrame) -> nexcore_error::Result<DataFrame> {
    tracing::info!(
        stage = "filter-new-types",
        expression = "module in ['location', 'frequency', 'bridges', 'gaps', 'exploratory']",
        "Applying filter"
    );
    // Permissive filter — passes all rows (stub, same as original)
    tracing::warn!(
        expression = "module in ['location', 'frequency', 'bridges', 'gaps', 'exploratory']",
        "Complex filter expression not fully parsed, using permissive filter"
    );
    Ok(df)
}
/// Transform: aggregate
pub fn transform_classify_tiers(df: DataFrame) -> nexcore_error::Result<DataFrame> {
    tracing::info!(stage = "classify-tiers", "Aggregating data");
    let aggregated = df
        .group_by(&["tier"])
        .map_err(|e| nexcore_error::nexerror!("{e}"))?
        .agg(&[Agg::Count, Agg::Mean("confidence".into())])
        .map_err(|e| nexcore_error::nexerror!("{e}"))?;
    Ok(aggregated)
}
/// Transform: aggregate
pub fn transform_dominant_distribution(df: DataFrame) -> nexcore_error::Result<DataFrame> {
    tracing::info!(stage = "dominant-distribution", "Aggregating data");
    let aggregated = df
        .group_by(&["dominant_primitive"])
        .map_err(|e| nexcore_error::nexerror!("{e}"))?
        .agg(&[Agg::Count])
        .map_err(|e| nexcore_error::nexerror!("{e}"))?;
    Ok(aggregated)
}
/// Sink: Write DataFrame to JSON file at output/pvos-expansion-report.json
pub fn sink_expansion_report(df: DataFrame) -> nexcore_error::Result<u64> {
    use nexcore_error::Context;

    tracing::info!(
        stage = "expansion-report",
        sink_type = "JsonFile",
        "Writing JSON output"
    );

    let row_count: u64 = u64::try_from(df.height()).unwrap_or_default();

    std::fs::create_dir_all("output").context("Failed to create output directory")?;

    let path = std::path::Path::new("output/pvos-expansion-report.json");
    df.to_json_file(path)
        .map_err(|e| nexcore_error::nexerror!("Failed to write JSON: {e}"))?;

    tracing::info!(
        records = row_count,
        path = "output/pvos-expansion-report.json",
        "Sink complete"
    );
    Ok(row_count)
}
