//! #description
//!
//! Generated by RustForge.
use nexcore_error::{Context, Result};
use clap::Parser;
use polars::prelude::*;
use pvos_primitive_expansion::*;
#[allow(unused_imports)]
use tracing::{error, info, instrument, warn};
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};
/// Pipeline CLI arguments.
#[derive(Parser, Debug)]
#[command(name = "pvos-primitive-expansion")]
#[command(version = "1.0.0")]
#[command(
    about = "Research-synthesized PVOS expansion: 17 primitive-grounded types across location, frequency, bridges, gaps, and exploratory modules. Ingests classification data, transforms via primitive grounding, outputs validation report."
)]
struct Args {
    /// Run once and exit (default behavior).
    #[arg(long)]
    once: bool,
    /// Dry run - validate configuration only.
    #[arg(long)]
    dry_run: bool,
    /// Verbose output (-v, -vv, -vvv).
    #[arg(short, long, action = clap::ArgAction::Count)]
    verbose: u8,
}
#[derive(Debug, Default)]
struct PipelineStats {
    records_processed: u64,
    records_written: u64,
    duration_secs: f64,
}
#[tokio::main]
async fn main() -> Result<()> {
    let args = Args::parse();
    let level = match args.verbose {
        0 => tracing::Level::INFO,
        1 => tracing::Level::DEBUG,
        _ => tracing::Level::TRACE,
    };
    tracing_subscriber::registry()
        .with(tracing_subscriber::fmt::layer().with_target(true))
        .with(tracing_subscriber::filter::LevelFilter::from_level(level))
        .init();
    info!(
        pipeline = "pvos-primitive-expansion",
        version = "1.0.0",
        "Starting pipeline"
    );
    if args.dry_run {
        info!("Dry run mode - validation only");
        return Ok(());
    }
    let result = run_pipeline().await;
    match result {
        Ok(stats) => {
            info!(
                records_processed = stats.records_processed,
                records_written = stats.records_written,
                duration_secs = stats.duration_secs,
                "Pipeline completed successfully"
            );
            Ok(())
        }
        Err(e) => {
            error!(error = % e, "Pipeline failed");
            Err(e)
        }
    }
}
#[instrument]
async fn run_pipeline() -> Result<PipelineStats> {
    let start = std::time::Instant::now();
    let mut stats = PipelineStats::default();
    info!(
        stage = "classification-data",
        source_type = "HttpJson",
        "Starting HTTP ingest"
    );
    let df = ingest_classification_data()
        .await
        .context(concat!("HTTP ingest failed: ", "classification-data"))?;
    stats.records_processed = df.height() as u64;
    info!(
        records = stats.records_processed,
        "Ingested records from HTTP"
    );
    let df = df.lazy();
    info!(
        stage = "filter-new-types",
        operation = "Filter",
        "Running transform"
    );
    let df = transform_filter_new_types(df)
        .context(concat!("Transform failed: ", "filter-new-types"))?;
    info!(
        stage = "classify-tiers",
        operation = "Aggregate",
        "Running transform"
    );
    let df =
        transform_classify_tiers(df).context(concat!("Transform failed: ", "classify-tiers"))?;
    info!(
        stage = "dominant-distribution",
        operation = "Aggregate",
        "Running transform"
    );
    let df = transform_dominant_distribution(df)
        .context(concat!("Transform failed: ", "dominant-distribution"))?;
    info!(
        stage = "expansion-report",
        sink_type = "JsonFile",
        "Running sink"
    );
    let written = sink_expansion_report(df)
        .await
        .context("Sink failed: expansion-report")?;
    stats.records_written = written;
    stats.duration_secs = start.elapsed().as_secs_f64();
    Ok(stats)
}
