//! Pipeline ingest, transform, and sink functions.
//!
//! Generated by RustForge.
/// Ingest stub for #source_str.
pub fn ingest_faers_data() -> anyhow::Result<polars::prelude::DataFrame> {
    tracing::warn!(
        stage = "faers-data", source = "S3Parquet", "Ingest not yet implemented"
    );
    panic!("Ingest source type not implemented: {}", "S3Parquet");
}
/// Transform: deduplicate
pub fn transform_deduplicate_cases(
    df: polars::prelude::LazyFrame,
) -> anyhow::Result<polars::prelude::LazyFrame> {
    use polars::prelude::*;
    tracing::info!(stage = "deduplicate-cases", "Deduplicating records");
    let subset_strs: &[&str] = &["case_id", "drug_name", "adverse_event"];
    let deduped = if subset_strs.is_empty() {
        df.unique_stable(None, UniqueKeepStrategy::First)
    } else {
        let subset: Vec<PlSmallStr> = subset_strs
            .iter()
            .map(|&s| PlSmallStr::from_static(s))
            .collect();
        df.unique_stable(Some(subset), UniqueKeepStrategy::First)
    };
    Ok(deduped)
}
/// Transform: PRR signal detection
/// Computes Proportional Reporting Ratio for pharmacovigilance.
pub fn transform_prr_detection(
    df: polars::prelude::LazyFrame,
) -> anyhow::Result<polars::prelude::LazyFrame> {
    use polars::prelude::*;
    tracing::info!(stage = "prr-detection", "Running PRR signal detection");
    let drug_col = "drug_name";
    let event_col = "adverse_event";
    let case_col = "case_id";
    let prr_threshold = 2f64;
    let chi_sq_threshold = 4f64;
    let min_cases = 3u32 as u32;
    let collected = df.clone().collect()?;
    let total_cases = collected.column(case_col)?.n_unique()? as f64;
    let drug_event_counts = df
        .clone()
        .group_by([col(drug_col), col(event_col)])
        .agg([col(case_col).n_unique().alias("a")]);
    let drug_totals = df
        .clone()
        .group_by([col(drug_col)])
        .agg([col(case_col).n_unique().alias("drug_total")]);
    let event_totals = df
        .clone()
        .group_by([col(event_col)])
        .agg([col(case_col).n_unique().alias("event_total")]);
    let with_drug_totals = drug_event_counts
        .join(
            drug_totals,
            [col(drug_col)],
            [col(drug_col)],
            JoinArgs::new(JoinType::Left),
        );
    let with_all_totals = with_drug_totals
        .join(
            event_totals,
            [col(event_col)],
            [col(event_col)],
            JoinArgs::new(JoinType::Left),
        );
    let total = lit(total_cases);
    let result = with_all_totals
        .with_columns([
            (col("drug_total") - col("a")).alias("b"),
            (col("event_total") - col("a")).alias("c"),
        ])
        .with_columns([(total.clone() - col("a") - col("b") - col("c")).alias("d")])
        .with_columns([
            ((col("a").cast(DataType::Float64)
                / (col("a") + col("b")).cast(DataType::Float64))
                / (col("c").cast(DataType::Float64)
                    / (col("c") + col("d")).cast(DataType::Float64)))
                .alias("prr"),
        ])
        .with_columns([
            {
                let ad = col("a").cast(DataType::Float64)
                    * col("d").cast(DataType::Float64);
                let bc = col("b").cast(DataType::Float64)
                    * col("c").cast(DataType::Float64);
                let n = total.clone();
                let ab = (col("a") + col("b")).cast(DataType::Float64);
                let cd = (col("c") + col("d")).cast(DataType::Float64);
                let ac = (col("a") + col("c")).cast(DataType::Float64);
                let bd = (col("b") + col("d")).cast(DataType::Float64);
                let diff = ad - bc;
                let numerator = diff.clone() * diff;
                let denominator = ab * cd * ac * bd;
                (numerator * n / denominator).alias("chi_squared")
            },
        ])
        .with_columns([
            (col("prr")
                .gt(lit(prr_threshold))
                .and(col("chi_squared").gt(lit(chi_sq_threshold)))
                .and(col("a").gt(lit(min_cases))))
                .alias("is_signal"),
        ])
        .filter(col("a").gt(lit(min_cases)));
    Ok(result)
}
/// Transform: filter
/// Expression: #expr_str
pub fn transform_filter_signals(
    df: polars::prelude::LazyFrame,
) -> anyhow::Result<polars::prelude::LazyFrame> {
    use polars::prelude::*;
    tracing::info!(
        stage = "filter-signals", expression = "is_signal == true", "Applying filter"
    );
    let filtered = df.filter(col("is_signal").eq(lit(true)));
    Ok(filtered)
}
/// Sink: Qdrant vector database
/// Collection: #collection
/// Vector column: #vector_column
pub async fn sink_vector_store(df: polars::prelude::LazyFrame) -> anyhow::Result<u64> {
    use polars::prelude::*;
    use anyhow::Context;
    use qdrant_client::qdrant::PointStruct;
    use std::collections::HashMap;
    tracing::info!(
        stage = "vector-store", collection = "signal_narratives", vector_column =
        "embedding", batch_size = 100u32, "Writing to Qdrant"
    );
    let collected = df.collect().context("Failed to collect DataFrame for Qdrant sink")?;
    let total_rows = collected.height();
    if total_rows == 0 {
        tracing::warn!(stage = "vector-store", "No rows to write to Qdrant");
        return Ok(0);
    }
    tracing::info!(
        stage = "vector-store", total_rows = total_rows, "Preparing to write rows"
    );
    let client = qdrant_client::Qdrant::from_url("http://localhost:6334")
        .build()
        .context("Failed to create Qdrant client")?;
    let mut all_points: Vec<PointStruct> = Vec::with_capacity(total_rows);
    let vector_series = collected
        .column("embedding")
        .context(concat!("Vector column not found: ", "embedding"))?;
    for row_idx in 0..total_rows {
        let vector: Vec<f32> = {
            let val = vector_series.get(row_idx)?;
            match val {
                AnyValue::List(series) => {
                    series
                        .f32()
                        .map(|ca| ca.into_iter().filter_map(|v| v).collect())
                        .or_else(|_| {
                            series
                                .f64()
                                .map(|ca| {
                                    ca.into_iter().filter_map(|v| v.map(|f| f as f32)).collect()
                                })
                        })
                        .context("Failed to extract vector values")?
                }
                _ => {
                    anyhow::bail!(
                        "Expected List type for vector column, got: {:?}", val.dtype()
                    );
                }
            }
        };
        if vector.is_empty() {
            tracing::warn!(row = row_idx, "Empty vector, skipping row");
            continue;
        }
        let row_df = collected.slice(row_idx as i64, 1);
        let point_id: u64 = row_idx as u64;
        let mut payload: HashMap<String, qdrant_client::qdrant::Value> = HashMap::new();
        if let Ok(series) = row_df.column("drug_name") {
            if let Ok(val) = series.get(0) {
                match val {
                    polars::prelude::AnyValue::String(s) => {
                        payload
                            .insert(
                                "drug_name".to_string(),
                                qdrant_client::qdrant::Value::from(s.to_string()),
                            );
                    }
                    polars::prelude::AnyValue::Int64(i) => {
                        payload
                            .insert(
                                "drug_name".to_string(),
                                qdrant_client::qdrant::Value::from(i),
                            );
                    }
                    polars::prelude::AnyValue::Float64(f) => {
                        payload
                            .insert(
                                "drug_name".to_string(),
                                qdrant_client::qdrant::Value::from(f),
                            );
                    }
                    polars::prelude::AnyValue::Boolean(b) => {
                        payload
                            .insert(
                                "drug_name".to_string(),
                                qdrant_client::qdrant::Value::from(b),
                            );
                    }
                    _ => {
                        payload
                            .insert(
                                "drug_name".to_string(),
                                qdrant_client::qdrant::Value::from(format!("{:?}", val)),
                            );
                    }
                }
            }
        }
        if let Ok(series) = row_df.column("adverse_event") {
            if let Ok(val) = series.get(0) {
                match val {
                    polars::prelude::AnyValue::String(s) => {
                        payload
                            .insert(
                                "adverse_event".to_string(),
                                qdrant_client::qdrant::Value::from(s.to_string()),
                            );
                    }
                    polars::prelude::AnyValue::Int64(i) => {
                        payload
                            .insert(
                                "adverse_event".to_string(),
                                qdrant_client::qdrant::Value::from(i),
                            );
                    }
                    polars::prelude::AnyValue::Float64(f) => {
                        payload
                            .insert(
                                "adverse_event".to_string(),
                                qdrant_client::qdrant::Value::from(f),
                            );
                    }
                    polars::prelude::AnyValue::Boolean(b) => {
                        payload
                            .insert(
                                "adverse_event".to_string(),
                                qdrant_client::qdrant::Value::from(b),
                            );
                    }
                    _ => {
                        payload
                            .insert(
                                "adverse_event".to_string(),
                                qdrant_client::qdrant::Value::from(format!("{:?}", val)),
                            );
                    }
                }
            }
        }
        if let Ok(series) = row_df.column("prr") {
            if let Ok(val) = series.get(0) {
                match val {
                    polars::prelude::AnyValue::String(s) => {
                        payload
                            .insert(
                                "prr".to_string(),
                                qdrant_client::qdrant::Value::from(s.to_string()),
                            );
                    }
                    polars::prelude::AnyValue::Int64(i) => {
                        payload
                            .insert(
                                "prr".to_string(),
                                qdrant_client::qdrant::Value::from(i),
                            );
                    }
                    polars::prelude::AnyValue::Float64(f) => {
                        payload
                            .insert(
                                "prr".to_string(),
                                qdrant_client::qdrant::Value::from(f),
                            );
                    }
                    polars::prelude::AnyValue::Boolean(b) => {
                        payload
                            .insert(
                                "prr".to_string(),
                                qdrant_client::qdrant::Value::from(b),
                            );
                    }
                    _ => {
                        payload
                            .insert(
                                "prr".to_string(),
                                qdrant_client::qdrant::Value::from(format!("{:?}", val)),
                            );
                    }
                }
            }
        }
        if let Ok(series) = row_df.column("chi_squared") {
            if let Ok(val) = series.get(0) {
                match val {
                    polars::prelude::AnyValue::String(s) => {
                        payload
                            .insert(
                                "chi_squared".to_string(),
                                qdrant_client::qdrant::Value::from(s.to_string()),
                            );
                    }
                    polars::prelude::AnyValue::Int64(i) => {
                        payload
                            .insert(
                                "chi_squared".to_string(),
                                qdrant_client::qdrant::Value::from(i),
                            );
                    }
                    polars::prelude::AnyValue::Float64(f) => {
                        payload
                            .insert(
                                "chi_squared".to_string(),
                                qdrant_client::qdrant::Value::from(f),
                            );
                    }
                    polars::prelude::AnyValue::Boolean(b) => {
                        payload
                            .insert(
                                "chi_squared".to_string(),
                                qdrant_client::qdrant::Value::from(b),
                            );
                    }
                    _ => {
                        payload
                            .insert(
                                "chi_squared".to_string(),
                                qdrant_client::qdrant::Value::from(format!("{:?}", val)),
                            );
                    }
                }
            }
        }
        if let Ok(series) = row_df.column("case_count") {
            if let Ok(val) = series.get(0) {
                match val {
                    polars::prelude::AnyValue::String(s) => {
                        payload
                            .insert(
                                "case_count".to_string(),
                                qdrant_client::qdrant::Value::from(s.to_string()),
                            );
                    }
                    polars::prelude::AnyValue::Int64(i) => {
                        payload
                            .insert(
                                "case_count".to_string(),
                                qdrant_client::qdrant::Value::from(i),
                            );
                    }
                    polars::prelude::AnyValue::Float64(f) => {
                        payload
                            .insert(
                                "case_count".to_string(),
                                qdrant_client::qdrant::Value::from(f),
                            );
                    }
                    polars::prelude::AnyValue::Boolean(b) => {
                        payload
                            .insert(
                                "case_count".to_string(),
                                qdrant_client::qdrant::Value::from(b),
                            );
                    }
                    _ => {
                        payload
                            .insert(
                                "case_count".to_string(),
                                qdrant_client::qdrant::Value::from(format!("{:?}", val)),
                            );
                    }
                }
            }
        }
        let point = PointStruct::new(point_id, vector, payload);
        all_points.push(point);
    }
    let points_count = all_points.len();
    tracing::info!(
        stage = "vector-store", points = points_count, "Constructed points for upsert"
    );
    let batch_size = 100u32 as usize;
    let mut written: u64 = 0;
    for (batch_idx, batch_points) in all_points.chunks(batch_size).enumerate() {
        let batch_points: Vec<PointStruct> = batch_points.to_vec();
        let batch_len = batch_points.len();
        tracing::debug!(
            stage = "vector-store", batch = batch_idx, points = batch_len,
            "Upserting batch"
        );
        client
            .upsert_points(
                qdrant_client::qdrant::UpsertPointsBuilder::new(
                    "signal_narratives",
                    batch_points,
                ),
            )
            .await
            .context(
                concat!(
                    "Failed to upsert points to Qdrant collection: ", "signal_narratives"
                ),
            )?;
        written += batch_len as u64;
        tracing::debug!(
            stage = "vector-store", batch = batch_idx, written = written,
            "Batch complete"
        );
    }
    tracing::info!(
        stage = "vector-store", collection = "signal_narratives", written = written,
        "Qdrant write complete"
    );
    Ok(written)
}
/// Sink: #sink_type_str (stub implementation)
pub async fn sink_postgres_signals(
    df: polars::prelude::LazyFrame,
) -> anyhow::Result<u64> {
    tracing::warn!(
        stage = "postgres-signals", sink_type = "Postgres",
        "Sink type not yet implemented"
    );
    panic!("Sink type not yet implemented: {}", "Postgres");
}
/// Sink: Parquet file output
/// Path template: #path_template
pub fn sink_parquet_archive(df: polars::prelude::LazyFrame) -> anyhow::Result<u64> {
    use polars::prelude::*;
    use anyhow::Context;
    tracing::info!(
        stage = "parquet-archive", path_template = "archive/signals-%Y%m%d.parquet",
        compression = stringify!(ParquetCompression::Zstd(None)), row_group_size =
        1000000u32, "Writing to Parquet"
    );
    let mut output_df = df
        .collect()
        .context("Failed to collect DataFrame for Parquet sink")?;
    let row_count = output_df.height() as u64;
    if row_count == 0 {
        tracing::warn!(stage = "parquet-archive", "No rows to write to Parquet");
        return Ok(0);
    }
    let path = chrono::Utc::now().format("archive/signals-%Y%m%d.parquet").to_string();
    if let Some(parent) = std::path::Path::new(&path).parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| {
                format!("Failed to create directory: {}", parent.display())
            })?;
    }
    let file = std::fs::File::create(&path)
        .with_context(|| format!("Failed to create Parquet file: {}", path))?;
    ParquetWriter::new(file)
        .with_compression(ParquetCompression::Zstd(None))
        .with_row_group_size(Some(1000000u32 as usize))
        .finish(&mut output_df)
        .with_context(|| format!("Failed to write Parquet file: {}", path))?;
    tracing::info!(
        stage = "parquet-archive", path = % path, rows = row_count,
        "Parquet write complete"
    );
    Ok(row_count)
}
