//! #description
//!
//! Generated by RustForge.
use anyhow::{Context, Result};
use clap::Parser;
#[allow(unused_imports)]
use tracing::{info, warn, error, instrument};
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};
use std::io::{self, BufRead, Write};
use polars::prelude::*;
use signal_detection::*;
/// Pipeline CLI arguments.
#[derive(Parser, Debug)]
#[command(name = "signal-detection")]
#[command(version = "0.1.0")]
#[command(about = "Pharmacovigilance signal detection using PRR algorithm")]
struct Args {
    /// Run once and exit (default behavior).
    #[arg(long)]
    once: bool,
    /// Dry run - validate configuration only.
    #[arg(long)]
    dry_run: bool,
    /// Verbose output (-v, -vv, -vvv).
    #[arg(short, long, action = clap::ArgAction::Count)]
    verbose: u8,
}
#[derive(Debug, Default)]
struct PipelineStats {
    records_processed: u64,
    records_written: u64,
    duration_secs: f64,
}
#[tokio::main]
async fn main() -> Result<()> {
    let args = Args::parse();
    let level = match args.verbose {
        0 => tracing::Level::INFO,
        1 => tracing::Level::DEBUG,
        _ => tracing::Level::TRACE,
    };
    tracing_subscriber::registry()
        .with(tracing_subscriber::fmt::layer().with_target(true))
        .with(tracing_subscriber::filter::LevelFilter::from_level(level))
        .init();
    info!(pipeline = "signal-detection", version = "0.1.0", "Starting pipeline");
    if args.dry_run {
        info!("Dry run mode - validation only");
        return Ok(());
    }
    let result = run_pipeline().await;
    match result {
        Ok(stats) => {
            info!(
                records_processed = stats.records_processed, records_written = stats
                .records_written, duration_secs = stats.duration_secs,
                "Pipeline completed successfully"
            );
            Ok(())
        }
        Err(e) => {
            error!(error = % e, "Pipeline failed");
            Err(e)
        }
    }
}
#[instrument]
async fn run_pipeline() -> Result<PipelineStats> {
    let start = std::time::Instant::now();
    let mut stats = PipelineStats::default();
    info!(stage = "faers-data", source_type = "S3Parquet", "Running ingest");
    panic!("Ingest source type not yet implemented: {}", "S3Parquet");
    #[allow(unreachable_code)]
    let df: LazyFrame = LazyFrame::default();
    info!(stage = "deduplicate-cases", operation = "Deduplicate", "Running transform");
    let df = transform_deduplicate_cases(df)
        .context(concat!("Transform failed: ", "deduplicate-cases"))?;
    info!(stage = "prr-detection", operation = "SignalDetectPrr", "Running transform");
    let df = transform_prr_detection(df)
        .context(concat!("Transform failed: ", "prr-detection"))?;
    info!(stage = "filter-signals", operation = "Filter", "Running transform");
    let df = transform_filter_signals(df)
        .context(concat!("Transform failed: ", "filter-signals"))?;
    info!(stage = "vector-store", sink_type = "Qdrant", "Writing to Qdrant");
    let written = sink_vector_store(df.clone())
        .await
        .context(concat!("Qdrant sink failed: ", "vector-store"))?;
    stats.records_written += written;
    info!(stage = "postgres-signals", sink_type = "Postgres", "Running sink");
    panic!("Sink type not yet implemented: {}", "Postgres");
    info!(stage = "parquet-archive", sink_type = "Parquet", "Writing to Parquet");
    let written = sink_parquet_archive(df.clone())
        .context(concat!("Parquet sink failed: ", "parquet-archive"))?;
    stats.records_written += written;
    stats.duration_secs = start.elapsed().as_secs_f64();
    Ok(stats)
}
